
const MAX_NESTED_DEPTH = 4;
function decodeText(buffer){const b=buffer instanceof Uint8Array?buffer:new Uint8Array(buffer);return new TextDecoder('utf-8').decode(b.length>=3&&b[0]===0xef&&b[1]===0xbb&&b[2]===0xbf?b.slice(3):b)}
function u16(b,o){return b[o]|(b[o+1]<<8)}
function u32(b,o){return (b[o]|(b[o+1]<<8)|(b[o+2]<<16)|(b[o+3]<<24))>>>0}
function kind(n){n=String(n||'').toLowerCase(); if(n.endsWith('.csv'))return'csv'; if(n.endsWith('.txt'))return'txt'; if(n.endsWith('.xlsx'))return'xlsx'; if(n.endsWith('.xlsm'))return'xlsm'; if(n.endsWith('.xls'))return'xls'; if(n.endsWith('.zip'))return'zip'; return''}
function isZip(b){return b&&b.length>=4&&b[0]===0x50&&b[1]===0x4b}
function eocd(b){for(let o=b.length-22;o>=Math.max(0,b.length-22-65535);o--){if(u32(b,o)===0x06054b50)return o}throw new Error('Could not find the ZIP central directory.')}
function entries(b){const e=eocd(b),total=u16(b,e+10),size=u32(b,e+12),start=u32(b,e+16); if(start<=0||start>=b.length||start+size>b.length)throw new Error('ZIP central directory appears invalid.'); let o=start,out=[]; for(let i=0;i<total;i++){if(u32(b,o)!==0x02014b50)throw new Error(`ZIP central directory entry ${i+1} is invalid.`); const flags=u16(b,o+8),method=u16(b,o+10),cs=u32(b,o+20),us=u32(b,o+24),fl=u16(b,o+28),el=u16(b,o+30),cl=u16(b,o+32),lho=u32(b,o+42); const name=decodeText(b.slice(o+46,o+46+fl)); out.push({fileName:name,flags,compressionMethod:method,compressedSize:cs,uncompressedSize:us,localHeaderOffset:lho,isDirectory:name.endsWith('/'),kind:kind(name)}); o=o+46+fl+el+cl} return out}
async function inflateRaw(bytes){if(typeof DecompressionStream!=='function')throw new Error('This browser cannot decompress ZIP files. Try Chrome/Edge, or unzip manually.'); for(const f of ['deflate-raw','deflate']){try{return new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream(f))).arrayBuffer())}catch(e){}} throw new Error('Could not decompress ZIP entry.')}
function compressed(b,e){const o=e.localHeaderOffset; if(o+30>b.length||u32(b,o)!==0x04034b50)throw new Error(`Local ZIP header for ${e.fileName} is invalid.`); const fl=u16(b,o+26),el=u16(b,o+28),s=o+30+fl+el,end=s+e.compressedSize; if(end>b.length)throw new Error(`ZIP entry ${e.fileName} appears truncated.`); return b.slice(s,end)}
async function data(b,e){const c=compressed(b,e); if(e.compressionMethod===0)return c; if(e.compressionMethod===8)return inflateRaw(c); throw new Error(`ZIP entry ${e.fileName} uses unsupported compression method ${e.compressionMethod}.`)}
async function walk(b,path='',depth=0){if(depth>MAX_NESTED_DEPTH)throw new Error(`Nested ZIP depth too deep at ${path||'root ZIP'}.`); if(!isZip(b))throw new Error(`${path||'Selected file'} does not appear to be a ZIP.`); const out=[]; for(const e of entries(b)){if(e.isDirectory||!e.kind)continue; const d=await data(b,e); if(!d?.length)continue; const name=path?`${path} / ${e.fileName}`:e.fileName; if(e.kind==='zip'){out.push(...await walk(d,name,depth+1)); continue} out.push({fileName:name,originalFileName:e.fileName,kind:e.kind,size:d.length||e.uncompressedSize,text:(e.kind==='csv'||e.kind==='txt')?decodeText(d):'',arrayBuffer:d.buffer.slice(d.byteOffset,d.byteOffset+d.byteLength)})} return out}
export async function extractSupplierFilesFromZip(file){const b=new Uint8Array(await file.arrayBuffer()); const files=await walk(b,file.name||'',0); if(!files.length)throw new Error('No CSV, TXT, XLS, XLSX, or XLSM files were found inside the ZIP or nested ZIPs.'); return files}
export async function extractCsvFilesFromZip(file){return extractSupplierFilesFromZip(file)}
