-- Step 6: WooCommerce order-status change audit.
-- ADDITIVE ONLY. No existing WooCommerce order, job, or inventory row is modified.

begin;
set local lock_timeout = '5s';
set local statement_timeout = '120s';

create table if not exists public.sc_woocommerce_status_change_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  employee_user_id uuid,
  employee_role text,
  woocommerce_order_id bigint not null,
  job_id bigint,
  previous_status text,
  requested_status text not null,
  resulting_status text,
  outcome text not null check (outcome in ('attempted', 'no_change', 'succeeded', 'failed')),
  note text,
  request_id text,
  woo_http_status integer,
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists sc_woo_status_audit_order_idx
  on public.sc_woocommerce_status_change_audit (woocommerce_order_id, created_at desc);
create index if not exists sc_woo_status_audit_user_idx
  on public.sc_woocommerce_status_change_audit (employee_user_id, created_at desc);
create index if not exists sc_woo_status_audit_outcome_idx
  on public.sc_woocommerce_status_change_audit (outcome, created_at desc);

alter table public.sc_woocommerce_status_change_audit enable row level security;
revoke all on public.sc_woocommerce_status_change_audit from public, anon, authenticated;
grant select, insert on public.sc_woocommerce_status_change_audit to service_role;

comment on table public.sc_woocommerce_status_change_audit is
  'Service-role audit trail for employee-initiated WooCommerce order status changes. Contains no WooCommerce credentials.';

insert into public.sc_application_schema_versions(version_key, phase, description, notes)
values (
  '202607250501',
  'step_6',
  'WooCommerce order status validation and audit support',
  'Additive audit table only. Existing order and job rows were not changed.'
)
on conflict (version_key) do update
set phase = excluded.phase,
    description = excluded.description,
    notes = excluded.notes;

commit;
