-- Skilled Crafting Google Calendar integration — Phase 1
-- Release: 0.6.30
--
-- This migration stores encrypted Google OAuth credentials, dedicated calendar
-- targets, stable application-to-calendar event mappings, and sync-run history.
-- Google credentials and events are accessed only through authenticated Netlify
-- functions using the Supabase service role.

begin;

create table if not exists public.sc_google_calendar_connections (
  singleton_key text primary key default 'primary',
  connected_by uuid,
  connected_email text,
  google_subject text,
  refresh_token_encrypted text,
  oauth_scope text,
  status text not null default 'disconnected',
  time_zone text not null default 'America/Los_Angeles',
  owner_employee_id text,
  owner_task_priority_min integer not null default 5,
  last_sync_at timestamptz,
  last_sync_status text,
  last_sync_error text,
  connected_at timestamptz,
  disconnected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sc_google_calendar_connections_singleton
    check (singleton_key = 'primary'),
  constraint sc_google_calendar_owner_priority_range
    check (owner_task_priority_min between 0 and 100)
);

create table if not exists public.sc_google_calendar_targets (
  event_kind text primary key,
  connection_key text not null default 'primary'
    references public.sc_google_calendar_connections(singleton_key)
    on delete cascade,
  calendar_summary text not null,
  google_calendar_id text not null,
  background_color text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sc_google_calendar_event_links (
  id bigint generated by default as identity primary key,
  event_kind text not null,
  source_table text not null,
  source_id text not null,
  google_calendar_id text not null,
  google_event_id text not null,
  event_hash text,
  google_etag text,
  source_updated_at timestamptz,
  sync_status text not null default 'pending',
  last_synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ux_sc_google_calendar_event_source
    unique (event_kind, source_id),
  constraint ux_sc_google_calendar_event_target
    unique (google_calendar_id, google_event_id)
);

create table if not exists public.sc_google_calendar_sync_runs (
  id bigint generated by default as identity primary key,
  trigger_source text not null default 'manual',
  requested_by text,
  status text not null default 'running',
  force_rebuild boolean not null default false,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  desired_events integer not null default 0,
  created_events integer not null default 0,
  updated_events integer not null default 0,
  deleted_events integer not null default 0,
  skipped_events integer not null default 0,
  error_count integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ix_sc_google_calendar_links_status
  on public.sc_google_calendar_event_links(sync_status, event_kind);

create index if not exists ix_sc_google_calendar_links_source
  on public.sc_google_calendar_event_links(source_table, source_id);

create index if not exists ix_sc_google_calendar_runs_started
  on public.sc_google_calendar_sync_runs(started_at desc);

-- Prevent a scheduled sync and a manual rebuild from running concurrently.
create unique index if not exists ux_sc_google_calendar_one_running_sync
  on public.sc_google_calendar_sync_runs(status)
  where status = 'running';

alter table public.sc_google_calendar_connections enable row level security;
alter table public.sc_google_calendar_targets enable row level security;
alter table public.sc_google_calendar_event_links enable row level security;
alter table public.sc_google_calendar_sync_runs enable row level security;

revoke all on table public.sc_google_calendar_connections from anon, authenticated;
revoke all on table public.sc_google_calendar_targets from anon, authenticated;
revoke all on table public.sc_google_calendar_event_links from anon, authenticated;
revoke all on table public.sc_google_calendar_sync_runs from anon, authenticated;

grant all on table public.sc_google_calendar_connections to service_role;
grant all on table public.sc_google_calendar_targets to service_role;
grant all on table public.sc_google_calendar_event_links to service_role;
grant all on table public.sc_google_calendar_sync_runs to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.sc_google_calendar_phase1_health()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $function$
  select jsonb_build_object(
    'installed', true,
    'connected', exists (
      select 1
      from public.sc_google_calendar_connections
      where singleton_key = 'primary'
        and status = 'connected'
        and nullif(refresh_token_encrypted, '') is not null
    ),
    'calendar_targets', (
      select count(*)
      from public.sc_google_calendar_targets
      where is_active
    ),
    'active_event_links', (
      select count(*)
      from public.sc_google_calendar_event_links
      where sync_status = 'synced'
    ),
    'last_successful_sync', (
      select max(finished_at)
      from public.sc_google_calendar_sync_runs
      where status = 'completed'
    ),
    'recent_failed_syncs', (
      select count(*)
      from public.sc_google_calendar_sync_runs
      where status = 'failed'
        and started_at >= now() - interval '24 hours'
    )
  );
$function$;

revoke all on function public.sc_google_calendar_phase1_health() from public;
grant execute on function public.sc_google_calendar_phase1_health() to service_role;

commit;

-- Expected result: all values are true.
select
  to_regclass('public.sc_google_calendar_connections') is not null
    as connection_table_installed,
  to_regclass('public.sc_google_calendar_targets') is not null
    as target_table_installed,
  to_regclass('public.sc_google_calendar_event_links') is not null
    as event_link_table_installed,
  to_regclass('public.sc_google_calendar_sync_runs') is not null
    as sync_run_table_installed,
  to_regprocedure('public.sc_google_calendar_phase1_health()') is not null
    as health_function_installed;
