-- Skilled Crafting Inventory v1.2.0
-- Product-to-blank mapping lifecycle
--
-- Additive and idempotent. This migration:
--   * records durable WooCommerce variation/SKU -> blank mappings;
--   * deterministically pairs synced products when Brand/Style/Color/Size has one match;
--   * repairs only currently unpaired pull-sheet lines;
--   * supports safe future-facing substitution of a discontinued blank;
--   * preserves mapping history and does not rewrite already paired job lines.

create extension if not exists pgcrypto;

create or replace function public.sc_mapping_norm_v1(p_value text)
returns text
language sql
immutable
parallel safe
as $$
  select trim(both '-' from regexp_replace(
    lower(translate(coalesce(p_value, ''), '&', ' ')),
    '[^a-z0-9]+', '-', 'g'
  ));
$$;

create table if not exists public.sc_product_blank_mappings (
  id uuid primary key default gen_random_uuid(),
  source_kind text not null check (source_kind in ('woocommerce_variation', 'woocommerce_sku', 'woocommerce_product')),
  source_key text not null,
  source_key_norm text not null,
  blank_product_id uuid not null references public.blank_products(id) on delete restrict,
  is_active boolean not null default true,
  mapping_source text not null default 'manual',
  notes text,
  superseded_at timestamptz,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists sc_product_blank_mappings_active_key_uidx
  on public.sc_product_blank_mappings(source_kind, source_key_norm)
  where is_active;

create index if not exists sc_product_blank_mappings_blank_idx
  on public.sc_product_blank_mappings(blank_product_id)
  where is_active;

create table if not exists public.sc_product_blank_mapping_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  source_kind text,
  source_key text,
  old_blank_product_id uuid references public.blank_products(id) on delete set null,
  new_blank_product_id uuid references public.blank_products(id) on delete set null,
  mapping_source text,
  notes text,
  affected jsonb not null default '{}'::jsonb,
  actor_id uuid,
  created_at timestamptz not null default now()
);

alter table public.sc_product_blank_mappings enable row level security;
alter table public.sc_product_blank_mapping_events enable row level security;

drop policy if exists sc_product_blank_mappings_read on public.sc_product_blank_mappings;
create policy sc_product_blank_mappings_read on public.sc_product_blank_mappings
  for select to authenticated using (true);

drop policy if exists sc_product_blank_mapping_events_read on public.sc_product_blank_mapping_events;
create policy sc_product_blank_mapping_events_read on public.sc_product_blank_mapping_events
  for select to authenticated using (true);

create or replace function public.sc_resolve_blank_product_v1(
  p_brand text,
  p_style text,
  p_color text,
  p_size text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_matches uuid[];
begin
  select coalesce(array_agg(bp.id order by bp.id), '{}'::uuid[])
    into v_matches
  from public.blank_products bp
  left join public.brands b on b.id = bp.brand_id
  left join public.product_types pt on pt.id = bp.product_type_id
  left join public.colors c on c.id = bp.color_id
  left join public.sizes s on s.id = bp.size_id
  where coalesce(bp.sc_is_archived, false) = false
    and public.sc_mapping_norm_v1(p_brand) in (public.sc_mapping_norm_v1(b.name), public.sc_mapping_norm_v1(b.code))
    and public.sc_mapping_norm_v1(p_style) in (public.sc_mapping_norm_v1(pt.name), public.sc_mapping_norm_v1(pt.code))
    and public.sc_mapping_norm_v1(p_color) in (public.sc_mapping_norm_v1(c.name), public.sc_mapping_norm_v1(c.code))
    and public.sc_mapping_norm_v1(p_size) in (public.sc_mapping_norm_v1(s.name), public.sc_mapping_norm_v1(s.code));

  return jsonb_build_object(
    'status', case cardinality(v_matches) when 0 then 'missing' when 1 then 'matched' else 'ambiguous' end,
    'candidate_count', cardinality(v_matches),
    'blank_product_id', case when cardinality(v_matches) = 1 then v_matches[1] else null end,
    'candidate_ids', to_jsonb(v_matches)
  );
end;
$$;

create or replace function public.sc_resolve_blank_matrix_v1(
  p_brand text,
  p_style text,
  p_colors text[],
  p_sizes text[]
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(jsonb_agg(
    jsonb_build_object('color', color_name, 'size', size_name) ||
    public.sc_resolve_blank_product_v1(p_brand, p_style, color_name, size_name)
    order by color_name, size_name
  ), '[]'::jsonb)
  from unnest(coalesce(p_colors, '{}'::text[])) color_name
  cross join unnest(coalesce(p_sizes, '{}'::text[])) size_name;
$$;

create or replace function public.sc_set_product_blank_mapping_v1(
  p_source_kind text,
  p_source_key text,
  p_blank_product_id uuid,
  p_mapping_source text default 'manual',
  p_notes text default null,
  p_propagate_unpaired boolean default true,
  p_actor_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_kind text := lower(trim(coalesce(p_source_kind, '')));
  v_key text := trim(coalesce(p_source_key, ''));
  v_norm text;
  v_old uuid;
  v_products integer := 0;
  v_lines integer := 0;
begin
  if v_kind not in ('woocommerce_variation', 'woocommerce_sku', 'woocommerce_product') then
    raise exception 'Unsupported mapping source kind: %', p_source_kind;
  end if;
  if v_key = '' then raise exception 'Mapping source key is required'; end if;
  if not exists (
    select 1 from public.blank_products
    where id = p_blank_product_id and coalesce(sc_is_archived, false) = false
  ) then
    raise exception 'The selected replacement blank does not exist or is archived';
  end if;

  v_norm := public.sc_mapping_norm_v1(v_key);
  perform pg_advisory_xact_lock(hashtext(v_kind || ':' || v_norm));

  select blank_product_id into v_old
  from public.sc_product_blank_mappings
  where source_kind = v_kind and source_key_norm = v_norm and is_active
  limit 1;

  update public.sc_product_blank_mappings
     set is_active = false, superseded_at = now(), updated_at = now()
   where source_kind = v_kind and source_key_norm = v_norm and is_active;

  insert into public.sc_product_blank_mappings(
    source_kind, source_key, source_key_norm, blank_product_id,
    mapping_source, notes, created_by
  ) values (
    v_kind, v_key, v_norm, p_blank_product_id,
    coalesce(nullif(trim(p_mapping_source), ''), 'manual'), nullif(trim(p_notes), ''), p_actor_id
  );

  if v_kind = 'woocommerce_variation' and v_key ~ '^[0-9]+$' then
    update public.products set blank_product_id = p_blank_product_id
     where woocommerce_variation_id = v_key::bigint
       and blank_product_id is distinct from p_blank_product_id;
    get diagnostics v_products = row_count;
    if p_propagate_unpaired then
      update public.job_items set
        blank_product_id = p_blank_product_id,
        pairing_source = 'remembered_variation_mapping',
        pairing_warning = null
      where blank_product_id is null and woocommerce_variation_id = v_key::bigint;
      get diagnostics v_lines = row_count;
    end if;
  elsif v_kind = 'woocommerce_sku' then
    update public.products set blank_product_id = p_blank_product_id
     where public.sc_mapping_norm_v1(sku) = v_norm
       and blank_product_id is distinct from p_blank_product_id;
    get diagnostics v_products = row_count;
    if p_propagate_unpaired then
      update public.job_items set
        blank_product_id = p_blank_product_id,
        pairing_source = 'remembered_sku_mapping',
        pairing_warning = null
      where blank_product_id is null
        and public.sc_mapping_norm_v1(coalesce(order_sku, sku)) = v_norm;
      get diagnostics v_lines = row_count;
    end if;
  elsif v_kind = 'woocommerce_product' and v_key ~ '^[0-9]+$' then
    update public.products set blank_product_id = p_blank_product_id
     where woocommerce_product_id = v_key::bigint
       and woocommerce_variation_id is null
       and blank_product_id is distinct from p_blank_product_id;
    get diagnostics v_products = row_count;
  end if;

  insert into public.sc_product_blank_mapping_events(
    event_type, source_kind, source_key, old_blank_product_id, new_blank_product_id,
    mapping_source, notes, affected, actor_id
  ) values (
    case when v_old is null then 'mapping_created' else 'mapping_replaced' end,
    v_kind, v_key, v_old, p_blank_product_id, p_mapping_source, p_notes,
    jsonb_build_object('products_updated', v_products, 'unpaired_lines_repaired', v_lines), p_actor_id
  );

  return jsonb_build_object(
    'source_kind', v_kind, 'source_key', v_key,
    'old_blank_product_id', v_old, 'blank_product_id', p_blank_product_id,
    'products_updated', v_products, 'unpaired_lines_repaired', v_lines
  );
end;
$$;

create or replace function public.sc_set_product_blank_mappings_bulk_v1(
  p_mappings jsonb,
  p_mapping_source text default 'bulk',
  p_notes text default null,
  p_propagate_unpaired boolean default true,
  p_actor_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row jsonb;
  v_count integer := 0;
  v_lines integer := 0;
  v_result jsonb;
begin
  if jsonb_typeof(coalesce(p_mappings, '[]'::jsonb)) <> 'array' then
    raise exception 'Mappings payload must be a JSON array';
  end if;
  for v_row in select value from jsonb_array_elements(coalesce(p_mappings, '[]'::jsonb))
  loop
    v_result := public.sc_set_product_blank_mapping_v1(
      v_row->>'source_kind', v_row->>'source_key', (v_row->>'blank_product_id')::uuid,
      p_mapping_source, p_notes, p_propagate_unpaired, p_actor_id
    );
    v_count := v_count + 1;
    v_lines := v_lines + coalesce((v_result->>'unpaired_lines_repaired')::integer, 0);
  end loop;
  return jsonb_build_object('mappings_saved', v_count, 'unpaired_lines_repaired', v_lines);
end;
$$;

create or replace function public.sc_product_blank_mapping_issues_v1(
  p_search text default '',
  p_limit integer default 250
)
returns table (
  product_row_id uuid,
  woo_product_id bigint,
  woo_variation_id bigint,
  sku text,
  product_name text,
  brand text,
  style text,
  color text,
  size text,
  issue_status text,
  deterministic_blank_product_id uuid,
  candidate_count integer
)
language sql
stable
security definer
set search_path = public
as $$
  with candidate_rows as (
    select
      p.id::uuid product_row_id,
      p.woocommerce_product_id::bigint woo_product_id,
      p.woocommerce_variation_id::bigint woo_variation_id,
      p.sku,
      p.name product_name,
      coalesce(b.name, b.code) brand,
      coalesce(pt.name, pt.code) style,
      coalesce(c.name, c.code) color,
      coalesce(s.name, s.code) size,
      public.sc_resolve_blank_product_v1(
        coalesce(b.name, b.code), coalesce(pt.name, pt.code),
        coalesce(c.name, c.code), coalesce(s.name, s.code)
      ) resolution
    from public.products p
    left join public.brands b on b.id = p.brand_id
    left join public.product_types pt on pt.id = p.product_type_id
    left join public.colors c on c.id = p.color_id
    left join public.sizes s on s.id = p.size_id
    where p.blank_product_id is null
      and (p.woocommerce_variation_id is not null or nullif(trim(coalesce(p.sku, '')), '') is not null)
      and (
        nullif(trim(coalesce(p_search, '')), '') is null
        or concat_ws(' ', p.sku, p.name, b.name, b.code, pt.name, pt.code, c.name, c.code, s.name, s.code)
             ilike '%' || replace(trim(p_search), '%', '') || '%'
      )
  )
  select product_row_id, woo_product_id, woo_variation_id, sku, product_name,
         brand, style, color, size,
         coalesce(resolution->>'status', 'missing_attributes') issue_status,
         nullif(resolution->>'blank_product_id', '')::uuid deterministic_blank_product_id,
         coalesce((resolution->>'candidate_count')::integer, 0) candidate_count
  from candidate_rows
  order by product_name nulls last, sku nulls last
  limit greatest(1, least(coalesce(p_limit, 250), 1000));
$$;

create or replace function public.sc_backfill_product_blank_mappings_v1(
  p_limit integer default 5000,
  p_actor_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row record;
  v_resolution jsonb;
  v_blank uuid;
  v_mapped integer := 0;
  v_review integer := 0;
begin
  for v_row in
    select p.*, coalesce(b.name, b.code) brand_name, coalesce(pt.name, pt.code) style_name,
           coalesce(c.name, c.code) color_name, coalesce(s.name, s.code) size_name
    from public.products p
    left join public.brands b on b.id = p.brand_id
    left join public.product_types pt on pt.id = p.product_type_id
    left join public.colors c on c.id = p.color_id
    left join public.sizes s on s.id = p.size_id
    where p.woocommerce_variation_id is not null or nullif(trim(coalesce(p.sku, '')), '') is not null
    order by p.id
    limit greatest(1, least(coalesce(p_limit, 5000), 20000))
  loop
    v_blank := v_row.blank_product_id;
    if v_blank is null then
      v_resolution := public.sc_resolve_blank_product_v1(v_row.brand_name, v_row.style_name, v_row.color_name, v_row.size_name);
      if v_resolution->>'status' = 'matched' then v_blank := (v_resolution->>'blank_product_id')::uuid; end if;
    end if;
    if v_blank is null then v_review := v_review + 1; continue; end if;

    if v_row.woocommerce_variation_id is not null then
      perform public.sc_set_product_blank_mapping_v1('woocommerce_variation', v_row.woocommerce_variation_id::text, v_blank, 'deterministic_backfill', null, true, p_actor_id);
    end if;
    if nullif(trim(coalesce(v_row.sku, '')), '') is not null then
      perform public.sc_set_product_blank_mapping_v1('woocommerce_sku', v_row.sku, v_blank, 'deterministic_backfill', null, true, p_actor_id);
    end if;
    v_mapped := v_mapped + 1;
  end loop;
  return jsonb_build_object('products_mapped', v_mapped, 'products_requiring_review', v_review);
end;
$$;

create or replace function public.sc_preview_blank_substitution_v1(
  p_old_blank_product_id uuid,
  p_new_blank_product_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  if p_old_blank_product_id = p_new_blank_product_id then raise exception 'Choose two different blank products'; end if;
  if not exists (select 1 from public.blank_products where id = p_old_blank_product_id) then raise exception 'Old blank product was not found'; end if;
  if not exists (select 1 from public.blank_products where id = p_new_blank_product_id and coalesce(sc_is_archived, false) = false) then raise exception 'Replacement blank product was not found or is archived'; end if;

  select jsonb_build_object(
    'active_mappings', (select count(*) from public.sc_product_blank_mappings where blank_product_id = p_old_blank_product_id and is_active),
    'products', (select count(*) from public.products where blank_product_id = p_old_blank_product_id),
    'finished_products', (select count(*) from public.finished_products where blank_product_id = p_old_blank_product_id),
    'open_paired_lines', (select count(*) from public.job_items where blank_product_id = p_old_blank_product_id and coalesce(status, '') !~* 'completed|cancel|void|deleted'),
    'unpaired_lines_eligible_for_repair', (select count(*) from public.job_items where blank_product_id is null and (woocommerce_variation_id is not null or nullif(trim(coalesce(order_sku, sku, '')), '') is not null)),
    'rule', 'Future catalog mappings change immediately. Already paired pull-sheet lines and inventory history are preserved.'
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.sc_apply_blank_substitution_v1(
  p_old_blank_product_id uuid,
  p_new_blank_product_id uuid,
  p_notes text default null,
  p_actor_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_preview jsonb;
  v_mappings integer := 0;
  v_products integer := 0;
  v_finished integer := 0;
  v_legacy integer := 0;
  v_repaired integer := 0;
begin
  v_preview := public.sc_preview_blank_substitution_v1(p_old_blank_product_id, p_new_blank_product_id);
  perform pg_advisory_xact_lock(hashtext('blank-substitution:' || p_old_blank_product_id::text));

  update public.sc_product_blank_mappings
     set blank_product_id = p_new_blank_product_id,
         mapping_source = 'blank_substitution', notes = coalesce(nullif(trim(p_notes), ''), notes), updated_at = now()
   where blank_product_id = p_old_blank_product_id and is_active;
  get diagnostics v_mappings = row_count;

  update public.products set blank_product_id = p_new_blank_product_id
   where blank_product_id = p_old_blank_product_id;
  get diagnostics v_products = row_count;

  update public.finished_products set blank_product_id = p_new_blank_product_id
   where blank_product_id = p_old_blank_product_id;
  get diagnostics v_finished = row_count;

  if to_regclass('public.product_sku_mappings') is not null then
    execute 'update public.product_sku_mappings set blank_product_id = $1 where blank_product_id = $2'
      using p_new_blank_product_id, p_old_blank_product_id;
    get diagnostics v_legacy = row_count;
  end if;

  -- Only fill lines that were never paired. Existing lines may already have reservations
  -- or physical work attached, so they remain unchanged for Bulk Pairing Repair review.
  update public.job_items ji set
    blank_product_id = m.blank_product_id,
    pairing_source = 'replacement_mapping',
    pairing_warning = null
  from public.sc_product_blank_mappings m
  where ji.blank_product_id is null and m.is_active
    and (
      (m.source_kind = 'woocommerce_variation' and ji.woocommerce_variation_id::text = m.source_key)
      or (m.source_kind = 'woocommerce_sku' and public.sc_mapping_norm_v1(coalesce(ji.order_sku, ji.sku)) = m.source_key_norm)
    );
  get diagnostics v_repaired = row_count;

  insert into public.sc_product_blank_mapping_events(
    event_type, old_blank_product_id, new_blank_product_id, mapping_source, notes, affected, actor_id
  ) values (
    'blank_substitution', p_old_blank_product_id, p_new_blank_product_id, 'blank_substitution', p_notes,
    jsonb_build_object('mappings', v_mappings, 'products', v_products, 'finished_products', v_finished,
      'legacy_mappings', v_legacy, 'unpaired_lines_repaired', v_repaired,
      'open_paired_lines_preserved', coalesce((v_preview->>'open_paired_lines')::integer, 0)), p_actor_id
  );

  return jsonb_build_object(
    'mappings_updated', v_mappings, 'products_updated', v_products,
    'finished_products_updated', v_finished, 'legacy_mappings_updated', v_legacy,
    'unpaired_lines_repaired', v_repaired,
    'open_paired_lines_preserved', coalesce((v_preview->>'open_paired_lines')::integer, 0)
  );
end;
$$;

-- Deterministic product sync: fill only when the four canonical attributes identify exactly one blank.
create or replace function public.sc_products_assign_deterministic_blank_v1()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_matches uuid[];
begin
  if new.blank_product_id is not null or new.brand_id is null or new.product_type_id is null or new.color_id is null or new.size_id is null then
    return new;
  end if;
  select coalesce(array_agg(bp.id), '{}'::uuid[]) into v_matches
  from public.blank_products bp
  where bp.brand_id = new.brand_id and bp.product_type_id = new.product_type_id
    and bp.color_id = new.color_id and bp.size_id = new.size_id
    and coalesce(bp.sc_is_archived, false) = false;
  if cardinality(v_matches) = 1 then new.blank_product_id := v_matches[1]; end if;
  return new;
end;
$$;

drop trigger if exists sc_products_assign_deterministic_blank_v1 on public.products;
create trigger sc_products_assign_deterministic_blank_v1
before insert or update of brand_id, product_type_id, color_id, size_id, blank_product_id
on public.products for each row execute function public.sc_products_assign_deterministic_blank_v1();

create or replace function public.sc_products_remember_blank_mapping_v1()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.blank_product_id is null then return new; end if;
  if new.woocommerce_variation_id is not null and not exists (
    select 1 from public.sc_product_blank_mappings m
    where m.source_kind = 'woocommerce_variation'
      and m.source_key_norm = public.sc_mapping_norm_v1(new.woocommerce_variation_id::text)
      and m.blank_product_id = new.blank_product_id and m.is_active
  ) then
    perform public.sc_set_product_blank_mapping_v1('woocommerce_variation', new.woocommerce_variation_id::text, new.blank_product_id, 'products_sync', null, true, null);
  end if;
  if nullif(trim(coalesce(new.sku, '')), '') is not null and not exists (
    select 1 from public.sc_product_blank_mappings m
    where m.source_kind = 'woocommerce_sku'
      and m.source_key_norm = public.sc_mapping_norm_v1(new.sku)
      and m.blank_product_id = new.blank_product_id and m.is_active
  ) then
    perform public.sc_set_product_blank_mapping_v1('woocommerce_sku', new.sku, new.blank_product_id, 'products_sync', null, true, null);
  end if;
  return new;
end;
$$;

drop trigger if exists sc_products_remember_blank_mapping_v1 on public.products;
create trigger sc_products_remember_blank_mapping_v1
after insert or update of woocommerce_variation_id, sku, blank_product_id
on public.products for each row
when (new.blank_product_id is not null)
execute function public.sc_products_remember_blank_mapping_v1();

revoke all on function public.sc_set_product_blank_mapping_v1(text,text,uuid,text,text,boolean,uuid) from public, anon, authenticated;
revoke all on function public.sc_set_product_blank_mappings_bulk_v1(jsonb,text,text,boolean,uuid) from public, anon, authenticated;
revoke all on function public.sc_apply_blank_substitution_v1(uuid,uuid,text,uuid) from public, anon, authenticated;
revoke all on function public.sc_backfill_product_blank_mappings_v1(integer,uuid) from public, anon, authenticated;
grant execute on function public.sc_resolve_blank_product_v1(text,text,text,text) to authenticated, service_role;
grant execute on function public.sc_resolve_blank_matrix_v1(text,text,text[],text[]) to authenticated, service_role;
grant execute on function public.sc_product_blank_mapping_issues_v1(text,integer) to authenticated, service_role;
grant execute on function public.sc_preview_blank_substitution_v1(uuid,uuid) to authenticated, service_role;
grant execute on function public.sc_set_product_blank_mapping_v1(text,text,uuid,text,text,boolean,uuid) to service_role;
grant execute on function public.sc_set_product_blank_mappings_bulk_v1(jsonb,text,text,boolean,uuid) to service_role;
grant execute on function public.sc_apply_blank_substitution_v1(uuid,uuid,text,uuid) to service_role;
grant execute on function public.sc_backfill_product_blank_mappings_v1(integer,uuid) to service_role;

notify pgrst, 'reload schema';
