-- Skilled Crafting Inventory v1.4.0
-- On-site production, authoritative purchasing availability, and catalog reconciliation.
-- Additive and safe to rerun. Does not create inventory quantities.

begin;
set local lock_timeout = '5s';
set local statement_timeout = '120s';

create table if not exists public.sc_onsite_production_orders (
  id bigint generated by default as identity primary key,
  production_number text unique,
  blank_product_id bigint not null references public.blank_products(id) on delete restrict,
  source_bin_id bigint not null references public.bins(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  customer_name text,
  player_name text,
  player_number text,
  personalization_color text,
  logo_name text,
  woo_category_id text,
  woo_product_id text,
  woo_variation_id text,
  label_size text not null default '4x6' check (label_size in ('2x3','4x6')),
  notes text,
  status text not null default 'produced' check (status in ('produced','voided')),
  inventory_movement_id bigint,
  created_by uuid,
  produced_at timestamptz not null default now(),
  voided_at timestamptz,
  voided_by uuid,
  void_reason text
);

create index if not exists ix_sc_onsite_orders_produced_at on public.sc_onsite_production_orders(produced_at desc);
create index if not exists ix_sc_onsite_orders_blank on public.sc_onsite_production_orders(blank_product_id, produced_at desc);

create table if not exists public.sc_color_drag_mappings (
  source_color_id bigint primary key references public.colors(id) on delete restrict,
  canonical_color_id bigint not null references public.colors(id) on delete restrict,
  reviewed_by text, notes text, is_active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check (source_color_id <> canonical_color_id)
);

create or replace function public.sc_save_color_drag_mappings_v1(
  p_source_color_ids_text text[], p_canonical_color_id_text text,
  p_notes text default null, p_reviewed_by text default null, p_apply_existing boolean default true
) returns jsonb language plpgsql security definer set search_path=public as $fn$
declare v_source_text text; v_source bigint; v_canonical bigint; v_saved integer:=0; v_products integer:=0; v_blanks integer:=0; v_skipped integer:=0; v_count integer;
begin
  v_canonical:=p_canonical_color_id_text::bigint;
  if not exists(select 1 from public.colors where id=v_canonical) then raise exception 'Choose a valid master color.'; end if;
  foreach v_source_text in array coalesce(p_source_color_ids_text,array[]::text[]) loop
    v_source:=v_source_text::bigint;
    if v_source=v_canonical then v_skipped:=v_skipped+1; continue; end if;
    insert into public.sc_color_drag_mappings(source_color_id,canonical_color_id,reviewed_by,notes)
    values(v_source,v_canonical,nullif(trim(p_reviewed_by),''),nullif(trim(p_notes),''))
    on conflict(source_color_id) do update set canonical_color_id=excluded.canonical_color_id,reviewed_by=excluded.reviewed_by,notes=excluded.notes,is_active=true,updated_at=now();
    v_saved:=v_saved+1;
    if p_apply_existing then
      update public.products set color_id=v_canonical where color_id=v_source;
      get diagnostics v_count=row_count; v_products:=v_products+v_count;
      update public.blank_products bp set color_id=v_canonical
      where bp.color_id=v_source and not exists(select 1 from public.blank_products twin where twin.id<>bp.id and twin.brand_id is not distinct from bp.brand_id and twin.product_type_id is not distinct from bp.product_type_id and twin.size_id is not distinct from bp.size_id and twin.color_id=v_canonical and coalesce(twin.sc_is_archived,false)=false);
      get diagnostics v_count=row_count; v_blanks:=v_blanks+v_count;
    end if;
  end loop;
  return jsonb_build_object('saved_rules',v_saved,'skipped',v_skipped,'products_updated',v_products,'blank_products_updated',v_blanks,'canonical_color_id',v_canonical);
end $fn$;

create or replace function public.sc_apply_drag_color_mapping_v1() returns trigger language plpgsql set search_path=public as $fn$
declare v_target bigint;
begin
  select canonical_color_id into v_target from public.sc_color_drag_mappings where source_color_id=new.color_id and is_active;
  if v_target is not null then new.color_id:=v_target; end if;
  return new;
end $fn$;
drop trigger if exists tr_sc_products_drag_color_map on public.products;
create trigger tr_sc_products_drag_color_map before insert or update of color_id on public.products for each row execute function public.sc_apply_drag_color_mapping_v1();
drop trigger if exists tr_sc_blanks_drag_color_map on public.blank_products;
create trigger tr_sc_blanks_drag_color_map before insert or update of color_id on public.blank_products for each row execute function public.sc_apply_drag_color_mapping_v1();

create or replace function public.sc_onsite_inventory_search_v1(p_search text default '', p_limit integer default 300)
returns table(
  blank_product_id bigint, sku_base text, blank_name text, brand text, style text,
  color text, size text, on_hand_quantity numeric, reserved_quantity numeric,
  available_quantity numeric
)
language sql stable security definer set search_path=public
as $fn$
  with movement as (
    select m.blank_product_id::bigint, sum(m.quantity_change)::numeric on_hand
    from public.blank_inventory_movements m group by m.blank_product_id
  ), reserved as (
    select r.blank_product_id::bigint,
      sum(greatest(coalesce(r.quantity_reserved, r.quantity, 0),0))::numeric reserved
    from public.inventory_reservations r
    where coalesce(lower(r.status::text),'active') not in ('released','cancelled','canceled','void','completed')
    group by r.blank_product_id
  )
  select bp.id::bigint, bp.sku_base::text, bp.name::text, b.name::text, pt.name::text,
    c.name::text, s.name::text, coalesce(m.on_hand,0), coalesce(r.reserved,0),
    greatest(coalesce(m.on_hand,0)-coalesce(r.reserved,0),0)
  from public.blank_products bp
  left join public.brands b on b.id=bp.brand_id
  left join public.product_types pt on pt.id=bp.product_type_id
  left join public.colors c on c.id=bp.color_id
  left join public.sizes s on s.id=bp.size_id
  left join movement m on m.blank_product_id=bp.id
  left join reserved r on r.blank_product_id=bp.id
  where coalesce(bp.sc_is_archived,false)=false
    and coalesce(m.on_hand,0)-coalesce(r.reserved,0)>0
    and (coalesce(trim(p_search),'')='' or concat_ws(' ',bp.sku_base,bp.name,b.name,pt.name,c.name,s.name) ilike '%'||trim(p_search)||'%')
  order by b.name,pt.name,c.name,s.name
  limit least(greatest(coalesce(p_limit,300),1),1000)
$fn$;

create or replace function public.sc_complete_onsite_sale_v1(
  p_blank_product_id bigint, p_customer_name text default null, p_player_name text default null,
  p_player_number text default null, p_personalization_color text default null,
  p_logo_name text default null, p_woo_category_id text default null,
  p_woo_product_id text default null, p_woo_variation_id text default null,
  p_label_size text default '4x6', p_notes text default null, p_created_by uuid default auth.uid()
) returns jsonb language plpgsql security definer set search_path=public as $fn$
declare
  v_bin record; v_order public.sc_onsite_production_orders%rowtype; v_movement_id bigint;
  v_reserved numeric := 0; v_blank record;
begin
  if p_blank_product_id is null then raise exception 'Choose an in-stock blank item.'; end if;
  perform pg_advisory_xact_lock(hashtext('sc-onsite-'||p_blank_product_id::text));
  select bp.*, b.name brand, pt.name style, c.name color, s.name size into v_blank
  from public.blank_products bp
  left join public.brands b on b.id=bp.brand_id left join public.product_types pt on pt.id=bp.product_type_id
  left join public.colors c on c.id=bp.color_id left join public.sizes s on s.id=bp.size_id
  where bp.id=p_blank_product_id and coalesce(bp.sc_is_archived,false)=false;
  if not found then raise exception 'The selected blank is missing or archived.'; end if;

  select coalesce(sum(greatest(coalesce(r.quantity_reserved,r.quantity,0),0)),0) into v_reserved
  from public.inventory_reservations r where r.blank_product_id=p_blank_product_id
    and coalesce(lower(r.status::text),'active') not in ('released','cancelled','canceled','void','completed');

  select m.bin_id, sum(m.quantity_change)::numeric on_hand, coalesce(b.label,b.bin_code,b.id::text) bin_label
  into v_bin from public.blank_inventory_movements m join public.bins b on b.id=m.bin_id
  where m.blank_product_id=p_blank_product_id
  group by m.bin_id,b.label,b.bin_code,b.id
  having sum(m.quantity_change)>0
  order by case when lower(concat_ws(' ',b.bin_code,b.label)) like '%pending%stock%' then 1 else 0 end,
    sum(m.quantity_change) desc,m.bin_id limit 1;
  if not found then raise exception 'No physical-bin inventory is available for this blank.'; end if;
  if (select coalesce(sum(quantity_change),0) from public.blank_inventory_movements where blank_product_id=p_blank_product_id) - v_reserved < 1 then
    raise exception 'This blank is on hand but reserved for another order. Choose another item.';
  end if;

  insert into public.sc_onsite_production_orders(blank_product_id,source_bin_id,customer_name,player_name,player_number,
    personalization_color,logo_name,woo_category_id,woo_product_id,woo_variation_id,label_size,notes,created_by)
  values(p_blank_product_id,v_bin.bin_id,nullif(trim(p_customer_name),''),nullif(trim(p_player_name),''),nullif(trim(p_player_number),''),
    nullif(trim(p_personalization_color),''),nullif(trim(p_logo_name),''),nullif(trim(p_woo_category_id),''),nullif(trim(p_woo_product_id),''),
    nullif(trim(p_woo_variation_id),''),case when p_label_size='2x3' then '2x3' else '4x6' end,nullif(trim(p_notes),''),p_created_by)
  returning * into v_order;
  update public.sc_onsite_production_orders set production_number='OS-'||to_char(produced_at,'YYYYMMDD')||'-'||lpad(id::text,6,'0') where id=v_order.id returning * into v_order;
  insert into public.blank_inventory_movements(bin_id,blank_product_id,quantity_change,movement_type,source_type,notes)
  values(v_bin.bin_id,p_blank_product_id,-1,'onsite_production','onsite_sale','[SC-ONSITE:'||v_order.id||'] '||coalesce(p_notes,'')) returning id into v_movement_id;
  update public.sc_onsite_production_orders set inventory_movement_id=v_movement_id where id=v_order.id;
  return jsonb_build_object('id',v_order.id,'production_number',v_order.production_number,'produced_at',v_order.produced_at,
    'label_size',v_order.label_size,'customer_name',v_order.customer_name,'player_name',v_order.player_name,'player_number',v_order.player_number,
    'personalization_color',v_order.personalization_color,'logo_name',v_order.logo_name,'source_bin_label',v_bin.bin_label,
    'blank_label',concat_ws(' • ',v_blank.brand,v_blank.style,v_blank.color,v_blank.size),'sku_base',v_blank.sku_base);
end $fn$;

-- One authoritative availability view for Purchasing. This prevents cached quantity
-- fields and duplicated source rows from overriding the movement ledger.
create or replace view public.sc_purchasing_authoritative_inventory_v3 with (security_invoker=true) as
with movement as (
  select blank_product_id::bigint, sum(quantity_change)::numeric quantity_on_hand
  from public.blank_inventory_movements group by blank_product_id
), reservation as (
  select blank_product_id::bigint,
    sum(greatest(coalesce(quantity_reserved,quantity,0),0))::numeric reserved_quantity
  from public.inventory_reservations
  where coalesce(lower(status::text),'active') not in ('released','cancelled','canceled','void','completed')
  group by blank_product_id
)
select bp.id::bigint blank_product_id, coalesce(m.quantity_on_hand,0) quantity_on_hand,
  coalesce(r.reserved_quantity,0) reserved_quantity,
  coalesce(m.quantity_on_hand,0)-coalesce(r.reserved_quantity,0) available_quantity,
  greatest(coalesce(r.reserved_quantity,0)-coalesce(m.quantity_on_hand,0),0) shortage_quantity,
  greatest(coalesce(r.reserved_quantity,0)+coalesce(bp.low_stock_threshold,0)-coalesce(m.quantity_on_hand,0),0) recommended_order_quantity
from public.blank_products bp left join movement m on m.blank_product_id=bp.id left join reservation r on r.blank_product_id=bp.id
where coalesce(bp.sc_is_archived,false)=false;

create or replace function public.sc_catalog_reconciliation_v2(p_search text default '',p_limit integer default 500)
returns table(issue_key text,severity text,issue_type text,woo_product_id text,woo_variation_id text,sku text,product_name text,blank_product_id text,message text,repair_action text)
language sql stable security definer set search_path=public as $fn$
with product_rows as (
 select p.*, bp.id matched_blank_id, bp.sc_is_archived blank_archived,
   b.name brand_name,pt.name style_name,c.name color_name,s.name size_name
 from public.products p left join public.blank_products bp on bp.id::text=p.blank_product_id::text
 left join public.brands b on b.id=p.brand_id left join public.product_types pt on pt.id=p.product_type_id
 left join public.colors c on c.id=p.color_id left join public.sizes s on s.id=p.size_id
 where coalesce(trim(p_search),'')='' or concat_ws(' ',p.sku,p.name,b.name,pt.name,c.name,s.name) ilike '%'||trim(p_search)||'%'
), issues as (
 select 'woo:'||coalesce(p.woocommerce_variation_id::text,p.id::text) issue_key,
   'high'::text severity,'missing_blank_mapping'::text issue_type,p.woocommerce_product_id::text,p.woocommerce_variation_id::text,p.sku::text,p.name::text,null::text,
   'WooCommerce variation has no active blank mapping.'::text message,'create_or_pair_blank'::text repair_action
 from product_rows p where p.blank_product_id is null
 union all
 select 'archived:'||p.id::text,'high','mapped_to_archived_blank',p.woocommerce_product_id::text,p.woocommerce_variation_id::text,p.sku::text,p.name::text,p.blank_product_id::text,
   'Variation maps to an archived blank. Choose a replacement blank.','replace_blank_mapping'
 from product_rows p where p.matched_blank_id is not null and coalesce(p.blank_archived,false)
 union all
 select 'missing:'||p.id::text,'high','missing_blank_record',p.woocommerce_product_id::text,p.woocommerce_variation_id::text,p.sku::text,p.name::text,p.blank_product_id::text,
   'Variation references a blank ID that does not exist.','rebuild_blank_mapping'
 from product_rows p where p.blank_product_id is not null and p.matched_blank_id is null
 union all
 select 'attributes:'||p.id::text,'medium','incomplete_variation_identity',p.woocommerce_product_id::text,p.woocommerce_variation_id::text,p.sku::text,p.name::text,p.blank_product_id::text,
   'Variation is missing SKU, brand, style, color, or size.','repair_woo_attributes'
 from product_rows p where nullif(trim(coalesce(p.sku::text,'')),'') is null or p.brand_id is null or p.product_type_id is null or p.color_id is null or p.size_id is null
)
select * from issues limit least(greatest(coalesce(p_limit,500),1),2000)
$fn$;

grant select on public.sc_onsite_production_orders,public.sc_purchasing_authoritative_inventory_v3 to authenticated,service_role;
grant select on public.sc_color_drag_mappings to authenticated,service_role;
grant execute on function public.sc_onsite_inventory_search_v1(text,integer),public.sc_complete_onsite_sale_v1(bigint,text,text,text,text,text,text,text,text,text,text,uuid),public.sc_catalog_reconciliation_v2(text,integer),public.sc_save_color_drag_mappings_v1(text[],text,text,text,boolean) to authenticated,service_role;

commit;
