-- Skilled Crafting Inventory v1.4.2
-- On-site Sales v2: category-level logo menu + cascading in-stock blank picker.
-- Adds a garment/item-type classification above Style without changing inventory quantities.

begin;
set local lock_timeout = '5s';
set local statement_timeout = '120s';

create table if not exists public.sc_blank_item_types (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sc_blank_item_types_name_key unique (name),
  constraint sc_blank_item_types_code_key unique (code)
);

insert into public.sc_blank_item_types(name,code,sort_order) values
  ('Tee','TEE',10),
  ('Hoodie','HOODIE',20),
  ('Sweatshirt','SWEATSHIRT',30),
  ('Quarter Zip','QUARTER-ZIP',40),
  ('Full Zip','FULL-ZIP',50),
  ('Polo','POLO',60),
  ('Jersey','JERSEY',70),
  ('Jacket','JACKET',80),
  ('Vest','VEST',90),
  ('Shorts','SHORTS',100),
  ('Pants','PANTS',110),
  ('Bag','BAG',120),
  ('Hat','HAT',130),
  ('Drinkware','DRINKWARE',140),
  ('Other','OTHER',900)
on conflict (code) do update set
  name=excluded.name,
  sort_order=excluded.sort_order,
  is_active=true,
  updated_at=now();

alter table public.product_types
  add column if not exists sc_item_type_id bigint references public.sc_blank_item_types(id) on delete set null;

create index if not exists ix_product_types_sc_item_type
  on public.product_types(sc_item_type_id, name);

-- Safe best-effort classification only where the style itself is descriptive.
-- Numeric/catalog style codes are intentionally left Unclassified rather than guessed.
update public.product_types pt
set sc_item_type_id = it.id
from public.sc_blank_item_types it
where pt.sc_item_type_id is null
  and (
    (it.code='HOODIE' and lower(concat_ws(' ',pt.name,pt.code)) like '%hoodie%') or
    (it.code='TEE' and (lower(concat_ws(' ',pt.name,pt.code)) like '% tee%' or lower(concat_ws(' ',pt.name,pt.code)) like 'tee%' or lower(concat_ws(' ',pt.name,pt.code)) like '%t-shirt%' or lower(concat_ws(' ',pt.name,pt.code)) like '%t shirt%')) or
    (it.code='SWEATSHIRT' and (lower(concat_ws(' ',pt.name,pt.code)) like '%sweatshirt%' or lower(concat_ws(' ',pt.name,pt.code)) like '%crewneck%')) or
    (it.code='QUARTER-ZIP' and (lower(concat_ws(' ',pt.name,pt.code)) like '%quarter zip%' or lower(concat_ws(' ',pt.name,pt.code)) like '%quarter-zip%' or lower(concat_ws(' ',pt.name,pt.code)) like '%1/4 zip%')) or
    (it.code='FULL-ZIP' and (lower(concat_ws(' ',pt.name,pt.code)) like '%full zip%' or lower(concat_ws(' ',pt.name,pt.code)) like '%full-zip%' or lower(concat_ws(' ',pt.name,pt.code)) like '%zip up%')) or
    (it.code='POLO' and lower(concat_ws(' ',pt.name,pt.code)) like '%polo%') or
    (it.code='JERSEY' and lower(concat_ws(' ',pt.name,pt.code)) like '%jersey%') or
    (it.code='JACKET' and lower(concat_ws(' ',pt.name,pt.code)) like '%jacket%') or
    (it.code='VEST' and lower(concat_ws(' ',pt.name,pt.code)) like '%vest%') or
    (it.code='SHORTS' and lower(concat_ws(' ',pt.name,pt.code)) like '%short%') or
    (it.code='PANTS' and (lower(concat_ws(' ',pt.name,pt.code)) like '%pant%' or lower(concat_ws(' ',pt.name,pt.code)) like '%jogger%')) or
    (it.code='BAG' and (lower(concat_ws(' ',pt.name,pt.code)) like '% bag%' or lower(concat_ws(' ',pt.name,pt.code)) like 'bag%' or lower(concat_ws(' ',pt.name,pt.code)) like '%backpack%' or lower(concat_ws(' ',pt.name,pt.code)) like '%tote%')) or
    (it.code='HAT' and (lower(concat_ws(' ',pt.name,pt.code)) like '%hat%' or lower(concat_ws(' ',pt.name,pt.code)) like '%cap%' or lower(concat_ws(' ',pt.name,pt.code)) like '%beanie%'))
  );

-- Keep v1 in place for compatibility. v2 exposes stable IDs for cascading selectors.
drop function if exists public.sc_onsite_inventory_search_v2(text,integer);
create function public.sc_onsite_inventory_search_v2(
  p_search text default '',
  p_limit integer default 5000
)
returns table(
  blank_product_id uuid,
  sku_base text,
  blank_name text,
  item_type_id bigint,
  item_type text,
  brand_id bigint,
  brand text,
  style_id bigint,
  style text,
  color_id bigint,
  color text,
  size_id bigint,
  size text,
  on_hand_quantity numeric,
  reserved_quantity numeric,
  available_quantity numeric
)
language sql stable security definer set search_path=public
as $fn$
  with movement as (
    select m.blank_product_id, sum(m.quantity_change)::numeric on_hand
    from public.blank_inventory_movements m
    group by m.blank_product_id
  ), reserved as (
    select r.blank_product_id,
      sum(greatest(coalesce(r.quantity_reserved,r.quantity,0),0))::numeric reserved
    from public.inventory_reservations r
    where coalesce(lower(r.status::text),'active') not in ('released','cancelled','canceled','void','completed')
    group by r.blank_product_id
  )
  select
    bp.id,
    bp.sku_base::text,
    bp.name::text,
    it.id,
    coalesce(it.name,'Unclassified')::text,
    b.id,
    b.name::text,
    pt.id,
    pt.name::text,
    c.id,
    c.name::text,
    s.id,
    s.name::text,
    coalesce(m.on_hand,0),
    coalesce(r.reserved,0),
    greatest(coalesce(m.on_hand,0)-coalesce(r.reserved,0),0)
  from public.blank_products bp
  left join public.brands b on b.id=bp.brand_id
  left join public.product_types pt on pt.id=bp.product_type_id
  left join public.sc_blank_item_types it on it.id=pt.sc_item_type_id and it.is_active
  left join public.colors c on c.id=bp.color_id
  left join public.sizes s on s.id=bp.size_id
  left join movement m on m.blank_product_id=bp.id
  left join reserved r on r.blank_product_id=bp.id
  where coalesce(bp.sc_is_archived,false)=false
    and coalesce(m.on_hand,0)-coalesce(r.reserved,0)>0
    and (
      coalesce(trim(p_search),'')='' or
      concat_ws(' ',bp.sku_base,bp.name,it.name,b.name,pt.name,c.name,s.name) ilike '%'||trim(p_search)||'%'
    )
  order by coalesce(it.sort_order,999),coalesce(it.name,'Unclassified'),b.name,pt.name,c.name,s.name
  limit least(greatest(coalesce(p_limit,5000),1),10000)
$fn$;

grant select on public.sc_blank_item_types to authenticated,service_role;
grant execute on function public.sc_onsite_inventory_search_v2(text,integer) to authenticated,service_role;

commit;
