-- Skilled Crafting Inventory App v1.4.16
-- SQL 63 - Pull Sheet / Purchasing Integrity
-- R3.3 corrections:
--   * removes duplicate blank_product_id columns from the fallback CTE
--   * does not count a LEFT JOIN null row as a mismatched reservation
--   * detects Pending Stock by bin_code OR label independently
--
-- Target: the v1.4.15 production model in which Purchasing already has:
--   * corrected authoritative inventory (sc_purchasing_authoritative_inventory_v3)
--   * reservation-backed demand sources
--   * Pending Stock line overrides
--   * independent non-inventory Purchasing inclusion
--
-- This migration adds a final integrity layer for active inventory-required
-- pull-sheet demand that is not represented by an active reservation.
--
-- SAFETY:
--   * no physical inventory quantity is changed
--   * no inventory movement row is created, deleted, or rewritten
--   * repair is service-role only
--   * safe exact product mappings may reconcile open, currently-unpaired job items
--   * placeholder MANUAL-<order>-LINE-<line> SKUs are never used as durable mappings
--
-- Safe to rerun.

begin;

set local lock_timeout = '5s';
set local statement_timeout = '120s';

do $guard$
begin
  if to_regclass('public.jobs') is null then
    raise exception 'Required table public.jobs is missing.';
  end if;
  if to_regclass('public.job_items') is null then
    raise exception 'Required table public.job_items is missing.';
  end if;
  if to_regclass('public.blank_products') is null then
    raise exception 'Required table public.blank_products is missing.';
  end if;
  if to_regclass('public.inventory_reservations') is null then
    raise exception 'Required table public.inventory_reservations is missing.';
  end if;
  if to_regclass('public.bins') is null then
    raise exception 'Required table public.bins is missing.';
  end if;
  if to_regclass('public.products') is null then
    raise exception 'Required table public.products is missing.';
  end if;
  if to_regclass('public.sc_purchasing_authoritative_inventory_v3') is null then
    raise exception 'Required view public.sc_purchasing_authoritative_inventory_v3 is missing.';
  end if;
  if to_regclass('public.purchasing_shortages') is null then
    raise exception 'Required view public.purchasing_shortages is missing.';
  end if;
  if to_regclass('public.purchasing_recommended_orders') is null then
    raise exception 'Required view public.purchasing_recommended_orders is missing.';
  end if;
  if to_regprocedure('public.sc_purchasing_status_is_active_v1(text)') is null then
    raise exception 'Required helper sc_purchasing_status_is_active_v1(text) is missing.';
  end if;
  if to_regprocedure('public.sc_purchasing_json_numeric_v1(jsonb,text[])') is null then
    raise exception 'Required helper sc_purchasing_json_numeric_v1(jsonb,text[]) is missing.';
  end if;
  if to_regprocedure('public.sc_purchasing_json_text_v1(jsonb,text[])') is null then
    raise exception 'Required helper sc_purchasing_json_text_v1(jsonb,text[]) is missing.';
  end if;
  if to_regprocedure('public.sc_ensure_job_item_reservation_v1(bigint,bigint,uuid,integer)') is null then
    raise exception 'Required reservation RPC sc_ensure_job_item_reservation_v1(bigint,bigint,uuid,integer) is missing.';
  end if;
end
$guard$;

create or replace function public.sc_ppi_pending_stock_bin_id_v1()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select b.id
  from public.bins b
  where lower(trim(coalesce(b.bin_code, ''))) in (
          'pending stock',
          'pending-stock',
          'pending_stock',
          'pendingstock'
        )
     or lower(trim(coalesce(b.label, ''))) = 'pending stock'
  order by b.display_order nulls last, b.id
  limit 1;
$$;

create table if not exists public.sc_pullsheet_purchasing_repair_log (
  id bigint generated by default as identity primary key,
  job_id bigint not null,
  actor_user_id uuid,
  repaired_job_items integer not null default 0,
  cancelled_mismatched_reservations integer not null default 0,
  reservations_ensured integer not null default 0,
  pending_stock_assignments integer not null default 0,
  physical_inventory_changed boolean not null default false,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.sc_pullsheet_purchasing_repair_log enable row level security;
revoke all on public.sc_pullsheet_purchasing_repair_log from public, anon, authenticated;
grant all on public.sc_pullsheet_purchasing_repair_log to service_role;

create or replace function public.sc_pullsheet_purchasing_integrity_v1(
  p_job_id bigint default null
)
returns table (
  job_id bigint,
  job_item_id bigint,
  blank_product_id uuid,
  ordered_quantity integer,
  inventory_required boolean,
  include_on_purchasing_report boolean,
  job_status text,
  job_item_status text,
  selected_bin_id bigint,
  selected_bin_is_pending boolean,
  correct_active_reservation_quantity integer,
  mismatched_active_reservation_count integer,
  quantity_on_hand integer,
  authoritative_reserved_quantity integer,
  authoritative_available_quantity integer,
  unreserved_line_quantity integer,
  expected_missing_quantity integer,
  issue_code text,
  issue_detail text
)
language sql
stable
security definer
set search_path = public
as $$
with active_lines as (
  select
    j.id as job_id,
    ji.id as job_item_id,
    ji.blank_product_id,
    greatest(
      coalesce(
        public.sc_purchasing_json_numeric_v1(to_jsonb(ji), 'quantity', 'qty'),
        0
      ),
      0
    )::integer as ordered_quantity,
    coalesce(
      nullif(to_jsonb(ji)->>'inventory_required', '')::boolean,
      true
    ) as inventory_required,
    coalesce(
      nullif(to_jsonb(ji)->>'include_on_purchasing_report', '')::boolean,
      true
    ) as include_on_purchasing_report,
    coalesce(
      public.sc_purchasing_json_text_v1(to_jsonb(j), 'status'),
      'queued'
    ) as job_status,
    coalesce(
      public.sc_purchasing_json_text_v1(to_jsonb(ji), 'status'),
      'queued'
    ) as job_item_status,
    public.sc_purchasing_json_numeric_v1(to_jsonb(ji), 'selected_bin_id')::bigint
      as selected_bin_id
  from public.job_items ji
  join public.jobs j on j.id = ji.job_id
  where (p_job_id is null or j.id = p_job_id)
    and public.sc_purchasing_status_is_active_v1(
      public.sc_purchasing_json_text_v1(to_jsonb(j), 'status')
    )
    and public.sc_purchasing_status_is_active_v1(
      public.sc_purchasing_json_text_v1(to_jsonb(ji), 'status')
    )
),
reservation_rows as (
  select
    public.sc_purchasing_json_numeric_v1(to_jsonb(r), 'job_item_id')::bigint
      as job_item_id,
    r.blank_product_id,
    greatest(
      coalesce(
        public.sc_purchasing_json_numeric_v1(
          to_jsonb(r),
          'quantity',
          'reserved_quantity'
        ),
        0
      ),
      0
    )::integer as quantity
  from public.inventory_reservations r
  where public.sc_purchasing_status_is_active_v1(
    public.sc_purchasing_json_text_v1(to_jsonb(r), 'status')
  )
),
reservation_summary as (
  select
    l.job_item_id,
    coalesce(sum(r.quantity) filter (
      where r.blank_product_id = l.blank_product_id
    ), 0)::integer as correct_active_reservation_quantity,
    count(r.job_item_id) filter (
      where r.blank_product_id is distinct from l.blank_product_id
    )::integer as mismatched_active_reservation_count
  from active_lines l
  left join reservation_rows r on r.job_item_id = l.job_item_id
  group by l.job_item_id
),
joined as (
  select
    l.*,
    (l.selected_bin_id is not null
      and l.selected_bin_id = public.sc_ppi_pending_stock_bin_id_v1()
    ) as selected_bin_is_pending,
    coalesce(rs.correct_active_reservation_quantity, 0)
      as correct_active_reservation_quantity,
    coalesce(rs.mismatched_active_reservation_count, 0)
      as mismatched_active_reservation_count,
    coalesce(
      public.sc_purchasing_json_numeric_v1(
        to_jsonb(ai),
        'quantity_on_hand',
        'on_hand_quantity',
        'on_hand',
        'total_quantity'
      ),
      0
    )::integer as quantity_on_hand,
    coalesce(
      public.sc_purchasing_json_numeric_v1(
        to_jsonb(ai),
        'reserved_quantity',
        'reserved_units',
        'reserved'
      ),
      0
    )::integer as authoritative_reserved_quantity,
    coalesce(
      public.sc_purchasing_json_numeric_v1(
        to_jsonb(ai),
        'available_quantity',
        'available_units',
        'available'
      ),
      coalesce(
        public.sc_purchasing_json_numeric_v1(
          to_jsonb(ai),
          'quantity_on_hand',
          'on_hand_quantity',
          'on_hand',
          'total_quantity'
        ),
        0
      )
      -
      coalesce(
        public.sc_purchasing_json_numeric_v1(
          to_jsonb(ai),
          'reserved_quantity',
          'reserved_units',
          'reserved'
        ),
        0
      )
    )::integer as authoritative_available_quantity
  from active_lines l
  left join reservation_summary rs on rs.job_item_id = l.job_item_id
  left join public.sc_purchasing_authoritative_inventory_v3 ai
    on ai.blank_product_id = l.blank_product_id
),
calculated as (
  select
    j.*,
    greatest(
      j.ordered_quantity - j.correct_active_reservation_quantity,
      0
    )::integer as unreserved_line_quantity
  from joined j
),
finalized as (
  select
    c.*,
    case
      when not c.inventory_required
        or not c.include_on_purchasing_report
        or c.blank_product_id is null
      then 0
      else greatest(
        c.unreserved_line_quantity
        - greatest(c.authoritative_available_quantity, 0),
        0
      )::integer
    end as expected_missing_quantity
  from calculated c
)
select
  f.job_id,
  f.job_item_id,
  f.blank_product_id,
  f.ordered_quantity,
  f.inventory_required,
  f.include_on_purchasing_report,
  f.job_status,
  f.job_item_status,
  f.selected_bin_id,
  f.selected_bin_is_pending,
  f.correct_active_reservation_quantity,
  f.mismatched_active_reservation_count,
  f.quantity_on_hand,
  f.authoritative_reserved_quantity,
  f.authoritative_available_quantity,
  f.unreserved_line_quantity,
  f.expected_missing_quantity,
  case
    when not f.inventory_required then 'non_inventory'
    when not f.include_on_purchasing_report then 'purchasing_excluded'
    when f.blank_product_id is null then 'missing_blank_pairing'
    when f.mismatched_active_reservation_count > 0 then 'reservation_blank_mismatch'
    when f.unreserved_line_quantity <= 0 then 'ok'
    when f.authoritative_available_quantity >= f.unreserved_line_quantity
      then 'reservation_repair_available'
    when f.expected_missing_quantity > 0
      then 'missing_purchasing_demand'
    else 'ok'
  end as issue_code,
  case
    when not f.inventory_required
      then 'This line intentionally does not use blank inventory.'
    when not f.include_on_purchasing_report
      then 'This line is intentionally excluded from Purchasing.'
    when f.blank_product_id is null
      then 'This active pull-sheet line has no paired blank product.'
    when f.mismatched_active_reservation_count > 0
      then 'An active reservation for this line points to a different blank product.'
    when f.unreserved_line_quantity <= 0
      then 'The pull-sheet quantity is represented by an active reservation.'
    when f.authoritative_available_quantity >= f.unreserved_line_quantity
      then 'Stock is available, but part of this pull-sheet quantity is not represented by an active reservation.'
    when f.expected_missing_quantity > 0
      then 'This pull-sheet line needs stock, but part of its demand is not represented by the reservation-backed Purchasing calculation.'
    else 'Pull-sheet and Purchasing state are aligned.'
  end as issue_detail
from finalized f
order by f.job_id desc, f.job_item_id;
$$;

revoke all on function public.sc_pullsheet_purchasing_integrity_v1(bigint)
  from public, anon;
grant execute on function public.sc_pullsheet_purchasing_integrity_v1(bigint)
  to authenticated, service_role;

-- Returns only the Purchasing adjustment attributable to open inventory-required
-- pull-sheet quantities that are not represented by an active correct reservation.
--
-- The adjustment is calculated against the same authoritative inventory view used
-- by the current v1.4.15 Purchasing client. Existing reservation-backed demand is
-- therefore not duplicated.
create or replace function public.sc_missing_pullsheet_purchasing_demand_v1()
returns table (
  blank_product_id uuid,
  sku_base text,
  name text,
  brand text,
  brand_code text,
  product_type text,
  product_type_code text,
  color text,
  color_code text,
  size text,
  size_code text,
  quantity_on_hand integer,
  reserved_quantity integer,
  available_quantity integer,
  low_stock_threshold integer,
  unit_cost numeric,
  need_to_order integer,
  recommended_order_quantity integer,
  estimated_order_value numeric,
  demand_source_count integer,
  demand_total_quantity integer,
  demand_order_numbers text,
  demand_pullsheet_numbers text,
  demand_sources jsonb,
  integrity_fallback boolean
)
language sql
stable
security definer
set search_path = public
as $$
with line_state as (
  select *
  from public.sc_pullsheet_purchasing_integrity_v1(null) ls
  where ls.inventory_required
    and ls.include_on_purchasing_report
    and ls.blank_product_id is not null
    and ls.unreserved_line_quantity > 0
),
grouped as (
  select
    ls.blank_product_id,
    sum(ls.unreserved_line_quantity)::integer as unreserved_quantity,
    count(*)::integer as source_count,
    string_agg(
      distinct ls.job_id::text,
      ', ' order by ls.job_id::text
    ) as pullsheet_numbers,
    jsonb_agg(
      jsonb_build_object(
        'job_id', ls.job_id,
        'pullsheet_number', ls.job_id,
        'pullsheet_label', 'Pull Sheet #' || ls.job_id::text,
        'job_item_id', ls.job_item_id,
        'quantity', ls.unreserved_line_quantity,
        'item_name', 'Integrity fallback — unrepresented pull-sheet demand',
        'pairing_source', 'pullsheet_purchasing_integrity',
        'pairing_warning',
          case
            when ls.issue_code = 'reservation_repair_available'
              then 'Reservation repair available: stock exists but the pull-sheet quantity is not fully reserved.'
            else 'Integrity fallback: this open pull-sheet quantity is not fully represented by active Purchasing reservations.'
          end
      )
      order by ls.job_id desc, ls.job_item_id desc
    ) as sources
  from line_state ls
  group by ls.blank_product_id
),
inventory_base as (
  select
    g.blank_product_id,
    g.unreserved_quantity,
    g.source_count,
    g.pullsheet_numbers,
    g.sources,
    coalesce(
      public.sc_purchasing_json_numeric_v1(
        to_jsonb(ai),
        'quantity_on_hand',
        'on_hand_quantity',
        'on_hand',
        'total_quantity'
      ),
      0
    )::integer as quantity_on_hand,
    coalesce(
      public.sc_purchasing_json_numeric_v1(
        to_jsonb(ai),
        'reserved_quantity',
        'reserved_units',
        'reserved'
      ),
      0
    )::integer as reserved_quantity,
    coalesce(
      public.sc_purchasing_json_numeric_v1(
        to_jsonb(ai),
        'available_quantity',
        'available_units',
        'available'
      ),
      coalesce(
        public.sc_purchasing_json_numeric_v1(
          to_jsonb(ai),
          'quantity_on_hand',
          'on_hand_quantity',
          'on_hand',
          'total_quantity'
        ),
        0
      )
      -
      coalesce(
        public.sc_purchasing_json_numeric_v1(
          to_jsonb(ai),
          'reserved_quantity',
          'reserved_units',
          'reserved'
        ),
        0
      )
    )::integer as available_quantity,
    bp.sku_base as bp_sku_base,
    bp.name as bp_name,
    coalesce(bp.unit_cost, 0)::numeric as bp_unit_cost,
    coalesce(bp.low_stock_threshold, 0)::integer as bp_threshold,
    br.name as bp_brand,
    br.code as bp_brand_code,
    pt.name as bp_product_type,
    pt.code as bp_product_type_code,
    clr.name as bp_color,
    clr.code as bp_color_code,
    sz.name as bp_size,
    sz.code as bp_size_code
  from grouped g
  join public.blank_products bp on bp.id = g.blank_product_id
  left join public.brands br on br.id = bp.brand_id
  left join public.product_types pt on pt.id = bp.product_type_id
  left join public.colors clr on clr.id = bp.color_id
  left join public.sizes sz on sz.id = bp.size_id
  left join public.sc_purchasing_authoritative_inventory_v3 ai
    on ai.blank_product_id = g.blank_product_id
),
calc as (
  select
    ib.*,
    (
      greatest(
        ib.reserved_quantity
        + ib.unreserved_quantity
        - ib.quantity_on_hand,
        0
      )
      -
      greatest(
        ib.reserved_quantity
        - ib.quantity_on_hand,
        0
      )
    )::integer as shortage_adjustment,
    (
      greatest(
        ib.reserved_quantity
        + ib.unreserved_quantity
        + ib.bp_threshold
        - ib.quantity_on_hand,
        0
      )
      -
      greatest(
        ib.reserved_quantity
        + ib.bp_threshold
        - ib.quantity_on_hand,
        0
      )
    )::integer as recommended_adjustment
  from inventory_base ib
)
select
  calc.blank_product_id,
  calc.bp_sku_base as sku_base,
  calc.bp_name as name,
  calc.bp_brand as brand,
  calc.bp_brand_code as brand_code,
  calc.bp_product_type as product_type,
  calc.bp_product_type_code as product_type_code,
  calc.bp_color as color,
  calc.bp_color_code as color_code,
  calc.bp_size as size,
  calc.bp_size_code as size_code,
  calc.quantity_on_hand,
  calc.reserved_quantity,
  calc.available_quantity,
  calc.bp_threshold as low_stock_threshold,
  calc.bp_unit_cost as unit_cost,
  greatest(calc.shortage_adjustment, 0)::integer as need_to_order,
  greatest(calc.recommended_adjustment, 0)::integer
    as recommended_order_quantity,
  (
    greatest(
      calc.recommended_adjustment,
      calc.shortage_adjustment,
      0
    )::numeric
    * calc.bp_unit_cost
  ) as estimated_order_value,
  calc.source_count as demand_source_count,
  calc.unreserved_quantity as demand_total_quantity,
  calc.pullsheet_numbers as demand_order_numbers,
  calc.pullsheet_numbers as demand_pullsheet_numbers,
  calc.sources as demand_sources,
  true as integrity_fallback
from calc
where calc.shortage_adjustment > 0
   or calc.recommended_adjustment > 0
order by greatest(
           calc.recommended_adjustment,
           calc.shortage_adjustment
         ) desc,
         calc.bp_sku_base;
$$;

revoke all on function public.sc_missing_pullsheet_purchasing_demand_v1()
  from public, anon;
grant execute on function public.sc_missing_pullsheet_purchasing_demand_v1()
  to authenticated, service_role;

create or replace function public.sc_repair_pullsheet_purchasing_integrity_v1(
  p_job_id bigint,
  p_actor uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_line record;
  v_pending_bin_id bigint;
  v_available integer;
  v_correct_reserved integer;
  v_unreserved integer;
  v_cancelled integer := 0;
  v_reservations_ensured integer := 0;
  v_pending_assignments integer := 0;
  v_repaired integer := 0;
  v_changed integer;
begin
  if p_job_id is null then
    raise exception 'A pull sheet/job ID is required.';
  end if;

  perform 1
  from public.jobs
  where id = p_job_id
  for update;

  if not found then
    raise exception 'Pull sheet/job % was not found.', p_job_id;
  end if;

  v_pending_bin_id := public.sc_ppi_pending_stock_bin_id_v1();
  if v_pending_bin_id is null then
    raise exception 'Pending Stock bin was not found.';
  end if;

  for v_line in
    select
      ji.id as job_item_id,
      ji.job_id,
      ji.blank_product_id,
      greatest(
        coalesce(
          public.sc_purchasing_json_numeric_v1(to_jsonb(ji), 'quantity', 'qty'),
          0
        ),
        0
      )::integer as quantity,
      public.sc_purchasing_json_numeric_v1(
        to_jsonb(ji),
        'selected_bin_id'
      )::bigint as selected_bin_id
    from public.job_items ji
    join public.jobs j on j.id = ji.job_id
    where ji.job_id = p_job_id
      and public.sc_purchasing_status_is_active_v1(
        public.sc_purchasing_json_text_v1(to_jsonb(j), 'status')
      )
      and public.sc_purchasing_status_is_active_v1(
        public.sc_purchasing_json_text_v1(to_jsonb(ji), 'status')
      )
      and coalesce(
        nullif(to_jsonb(ji)->>'inventory_required', '')::boolean,
        true
      )
      and coalesce(
        nullif(to_jsonb(ji)->>'include_on_purchasing_report', '')::boolean,
        true
      )
      and ji.blank_product_id is not null
    order by ji.id
    for update of ji
  loop
    update public.inventory_reservations r
    set status = 'cancelled'
    where public.sc_purchasing_json_numeric_v1(
            to_jsonb(r),
            'job_item_id'
          )::bigint = v_line.job_item_id
      and public.sc_purchasing_status_is_active_v1(
        public.sc_purchasing_json_text_v1(to_jsonb(r), 'status')
      )
      and r.blank_product_id is distinct from v_line.blank_product_id;

    get diagnostics v_changed = row_count;
    v_cancelled := v_cancelled + v_changed;

    select
      coalesce(sum(
        greatest(
          coalesce(
            public.sc_purchasing_json_numeric_v1(
              to_jsonb(r),
              'quantity',
              'reserved_quantity'
            ),
            0
          ),
          0
        )
      ), 0)::integer
    into v_correct_reserved
    from public.inventory_reservations r
    where public.sc_purchasing_json_numeric_v1(
            to_jsonb(r),
            'job_item_id'
          )::bigint = v_line.job_item_id
      and r.blank_product_id = v_line.blank_product_id
      and public.sc_purchasing_status_is_active_v1(
        public.sc_purchasing_json_text_v1(to_jsonb(r), 'status')
      );

    v_unreserved := greatest(v_line.quantity - coalesce(v_correct_reserved, 0), 0);

    select coalesce(
      public.sc_purchasing_json_numeric_v1(
        to_jsonb(ai),
        'available_quantity',
        'available_units',
        'available'
      ),
      0
    )::integer
    into v_available
    from public.sc_purchasing_authoritative_inventory_v3 ai
    where ai.blank_product_id = v_line.blank_product_id;

    v_available := coalesce(v_available, 0);

    if v_line.quantity > 0
       and v_unreserved > 0
       and v_available >= v_unreserved then
      perform public.sc_ensure_job_item_reservation_v1(
        v_line.job_id,
        v_line.job_item_id,
        v_line.blank_product_id,
        v_line.quantity
      );
      v_reservations_ensured := v_reservations_ensured + 1;

      if v_line.selected_bin_id = v_pending_bin_id then
        update public.job_items
        set selected_bin_id = null
        where id = v_line.job_item_id;
      end if;
    elsif v_unreserved > v_available then
      if v_line.selected_bin_id is null
         or v_line.selected_bin_id = v_pending_bin_id then
        update public.job_items
        set selected_bin_id = v_pending_bin_id
        where id = v_line.job_item_id
          and selected_bin_id is distinct from v_pending_bin_id;

        get diagnostics v_changed = row_count;
        v_pending_assignments := v_pending_assignments + v_changed;
      end if;
    end if;

    v_repaired := v_repaired + 1;
  end loop;

  insert into public.sc_pullsheet_purchasing_repair_log(
    job_id,
    actor_user_id,
    repaired_job_items,
    cancelled_mismatched_reservations,
    reservations_ensured,
    pending_stock_assignments,
    physical_inventory_changed,
    result
  ) values (
    p_job_id,
    p_actor,
    v_repaired,
    v_cancelled,
    v_reservations_ensured,
    v_pending_assignments,
    false,
    jsonb_build_object(
      'success', true,
      'job_id', p_job_id,
      'repaired_job_items', v_repaired,
      'cancelled_mismatched_reservations', v_cancelled,
      'reservations_ensured', v_reservations_ensured,
      'pending_stock_assignments', v_pending_assignments,
      'physical_inventory_changed', false
    )
  );

  return jsonb_build_object(
    'success', true,
    'job_id', p_job_id,
    'repaired_job_items', v_repaired,
    'cancelled_mismatched_reservations', v_cancelled,
    'reservations_ensured', v_reservations_ensured,
    'pending_stock_assignments', v_pending_assignments,
    'physical_inventory_changed', false,
    'message', format(
      'Reconciled %s active pull-sheet line(s); %s reservation(s) ensured; %s line(s) assigned to Pending Stock.',
      v_repaired,
      v_reservations_ensured,
      v_pending_assignments
    )
  );
end;
$$;

revoke all on function public.sc_repair_pullsheet_purchasing_integrity_v1(bigint,uuid)
  from public, anon, authenticated;
grant execute on function public.sc_repair_pullsheet_purchasing_integrity_v1(bigint,uuid)
  to service_role;

-- Exact product -> blank mapping reconciliation for already-open work.
--
-- This closes the New Product Line Setup gap without introducing fuzzy identity
-- matching. It only fills currently-null job_items.blank_product_id values when
-- the job item carries an exact Woo ID or exact reusable SKU.
create or replace function public.sc_reconcile_product_mapping_to_open_pullsheet_v1()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_product jsonb;
  v_wp_id text;
  v_sku text;
  v_job record;
begin
  if new.blank_product_id is null
     or new.blank_product_id is not distinct from old.blank_product_id then
    return new;
  end if;

  v_product := to_jsonb(new);
  v_wp_id := nullif(trim(coalesce(
    v_product->>'wp_post_id',
    v_product->>'woocommerce_variation_id',
    v_product->>'woocommerce_product_id',
    ''
  )), '');
  v_sku := nullif(trim(coalesce(v_product->>'sku', '')), '');

  update public.job_items ji
  set blank_product_id = new.blank_product_id
  from public.jobs j
  where j.id = ji.job_id
    and ji.blank_product_id is null
    and coalesce(
      nullif(to_jsonb(ji)->>'inventory_required', '')::boolean,
      true
    )
    and public.sc_purchasing_status_is_active_v1(
      public.sc_purchasing_json_text_v1(to_jsonb(j), 'status')
    )
    and public.sc_purchasing_status_is_active_v1(
      public.sc_purchasing_json_text_v1(to_jsonb(ji), 'status')
    )
    and (
      (
        v_wp_id is not null
        and (
          nullif(trim(coalesce(
            to_jsonb(ji)->>'woocommerce_variation_id',
            ''
          )), '') = v_wp_id
          or (
            nullif(trim(coalesce(
              to_jsonb(ji)->>'woocommerce_variation_id',
              ''
            )), '') is null
            and nullif(trim(coalesce(
              to_jsonb(ji)->>'woocommerce_product_id',
              ''
            )), '') = v_wp_id
          )
        )
      )
      or (
        v_sku is not null
        and v_sku !~* '^MANUAL-[0-9]+-LINE-[0-9]+$'
        and lower(trim(coalesce(
          to_jsonb(ji)->>'order_sku',
          to_jsonb(ji)->>'sku',
          ''
        ))) = lower(v_sku)
      )
    );

  for v_job in
    select distinct ji.job_id
    from public.job_items ji
    join public.jobs j on j.id = ji.job_id
    where ji.blank_product_id = new.blank_product_id
      and public.sc_purchasing_status_is_active_v1(
        public.sc_purchasing_json_text_v1(to_jsonb(j), 'status')
      )
      and public.sc_purchasing_status_is_active_v1(
        public.sc_purchasing_json_text_v1(to_jsonb(ji), 'status')
      )
      and coalesce(
        nullif(to_jsonb(ji)->>'inventory_required', '')::boolean,
        true
      )
      and (
        (
          v_wp_id is not null
          and (
            nullif(trim(coalesce(
              to_jsonb(ji)->>'woocommerce_variation_id',
              ''
            )), '') = v_wp_id
            or (
              nullif(trim(coalesce(
                to_jsonb(ji)->>'woocommerce_variation_id',
                ''
              )), '') is null
              and nullif(trim(coalesce(
                to_jsonb(ji)->>'woocommerce_product_id',
                ''
              )), '') = v_wp_id
            )
          )
        )
        or (
          v_sku is not null
          and v_sku !~* '^MANUAL-[0-9]+-LINE-[0-9]+$'
          and lower(trim(coalesce(
            to_jsonb(ji)->>'order_sku',
            to_jsonb(ji)->>'sku',
            ''
          ))) = lower(v_sku)
        )
      )
  loop
    perform public.sc_repair_pullsheet_purchasing_integrity_v1(
      v_job.job_id,
      null
    );
  end loop;

  return new;
end;
$$;

revoke all on function public.sc_reconcile_product_mapping_to_open_pullsheet_v1()
  from public, anon, authenticated;

drop trigger if exists trg_sc_reconcile_product_mapping_to_open_pullsheet_v1
  on public.products;

create trigger trg_sc_reconcile_product_mapping_to_open_pullsheet_v1
after update of blank_product_id on public.products
for each row
when (
  new.blank_product_id is not null
  and old.blank_product_id is distinct from new.blank_product_id
)
execute function public.sc_reconcile_product_mapping_to_open_pullsheet_v1();

notify pgrst, 'reload schema';

commit;
