export const TRAINING_VERSION = '1.0';

export const trainingRoles = [
  { id: 'new-employee', label: 'New Employee', description: 'Start here. Learn the daily workflow, safety rules, receiving, pull sheets, and how to avoid inventory mistakes.' },
  { id: 'warehouse', label: 'Receiving / Warehouse', description: 'Receiving, bins, scanning, transfers, audits, supplier deliveries, and physical inventory accuracy.' },
  { id: 'production', label: 'Production', description: 'Pull sheets, reservations, production sequencing, deductions, spoilage, QC, and finished goods.' },
  { id: 'artwork', label: 'Artwork / Customer Admin', description: 'Client orders, artwork requests, Mockup Studio, approvals, order details, and customer-facing handoffs.' },
  { id: 'manager', label: 'Manager', description: 'Daily command center, order risk, purchasing, production coordination, exception handling, and deadlines.' },
  { id: 'owner-admin', label: 'Owner / Admin', description: 'Full-system operations, product mapping, integrations, pricing, health tools, troubleshooting, and deployment.' },
];

const step = (title, instruction, options = {}) => ({ title, instruction, ...options });

export const trainingTutorials = [
  {
    id: 'orientation-101',
    title: 'Orientation: Learn the System Without Breaking Anything',
    roles: ['new-employee','warehouse','production','artwork','manager','owner-admin'],
    level: 'Required',
    minutes: 20,
    safeMode: 'read-only',
    summary: 'Learn the vocabulary, where work starts, where inventory truth lives, and which actions are safe to explore.',
    outcome: 'The employee can explain the difference between WooCommerce demand, blank inventory, reservations, jobs, pull sheets, bins, Pending Stock, and finished inventory.',
    steps: [
      step('Open the Application Guide', 'Open this guide and bookmark it. Search for a task before guessing how a workflow works.', { route: '/application-guide', verify: 'You can find the Inventory, Production, Purchasing, Artwork, and Training chapters.' }),
      step('Open the Daily Command Center', 'Look at the current operational summary. Do not change anything.', { route: '/command-center', verify: 'You can identify jobs at risk, shortages, and important exceptions.' }),
      step('Open Inventory Overview', 'Search for one common blank item and inspect On Hand, Reserved, Available, and bin information.', { route: '/inventory/blanks', verify: 'You can explain why Available may be lower than On Hand.' }),
      step('Open a Pull Sheet', 'Open an existing pull sheet in read-only fashion and identify the customer/order, blank item, quantity, bin, and status.', { route: '/pullsheets', verify: 'You can point out what must be physically pulled and what is only planning data.' }),
      step('Review the safety rules', 'Read the Safety Rules section in the guide before performing any inventory-changing action.', { route: '/application-guide#safety-rules', verify: 'You know not to receive into Pending Stock and not to fix mapping problems by changing quantity.' }),
    ],
    coachNotes: ['Do this tutorial with a manager on the employee’s first day.', 'The employee should be able to explain the workflow back in their own words before moving to receiving or production tasks.'],
  },
  {
    id: 'receiving-101',
    title: 'Receiving 101: Put Physical Inventory Into the Right Bin',
    roles: ['new-employee','warehouse','manager','owner-admin'],
    level: 'Core',
    minutes: 25,
    safeMode: 'supervised-live',
    summary: 'Practice the exact decision process used when supplier goods arrive.',
    outcome: 'The employee can receive an exact Brand + Style + Color + Size into the real physical bin and verify the result.',
    steps: [
      step('Before touching the app, count the shipment', 'Separate items by exact style, color, and size. Count the physical units first.', { verify: 'You have a physical quantity for each exact variation.' }),
      step('Open Add Item to Bin', 'Use manual receiving for a small shipment or local purchase.', { route: '/add-item', verify: 'You can identify destination bin, product, quantity, and notes fields.' }),
      step('Find the exact blank', 'Search by SKU or Brand + Style + Color + Size. Never choose a near match just to continue.', { warning: 'If the exact item cannot be found, stop and ask a manager before creating a new blank.' }),
      step('Choose the real destination bin', 'Select the bin where the garment will physically be stored.', { warning: 'Pending Stock is not a physical bin and must never be used for receiving.' }),
      step('Enter actual quantity received', 'Use what physically arrived, not what the supplier invoice says should have arrived.'),
      step('Complete receiving and put away immediately', 'Finish the receiving action, then place the goods in the selected bin.', { verify: 'Inventory Overview and Bin Contents show the new quantity in the same physical location.' }),
    ],
    coachNotes: ['First live receipt should be supervised.', 'Use a small 1–3 line receipt before allowing bulk supplier receiving.'],
  },
  {
    id: 'supplier-receiving-201',
    title: 'Supplier Receiving: Larger Orders and Partial Deliveries',
    roles: ['warehouse','manager','owner-admin'],
    level: 'Intermediate',
    minutes: 35,
    safeMode: 'supervised-live',
    summary: 'Receive supplier confirmation files safely, including mismatches and partial shipments.',
    outcome: 'The employee can distinguish matched, review, and unmatched supplier lines and avoid duplicate receiving.',
    steps: [
      step('Open supplier receiving', 'Open the supplier confirmation receiving workflow and upload a supported supplier document.', { route: '/add-item', verify: 'The parsed lines show product identity and quantities.' }),
      step('Review every warning row', 'Do not bulk-receive yellow/red or uncertain matches.', { warning: 'A similar color or style is not automatically the same product.' }),
      step('Correct product identity before quantity', 'Resolve Brand, Style, Color, Size, or supplier mapping issues first.' }),
      step('Enter actual received quantities', 'If only part of an order arrived, receive only the units in the box.' }),
      step('Verify after timeouts', 'If the browser times out, check inventory/receipt history before clicking Receive again.', { warning: 'Retrying a completed receipt can duplicate inventory.' }),
    ],
  },
  {
    id: 'pullsheet-101',
    title: 'Pull Sheet 101: Pull the Correct Blank and Protect Inventory',
    roles: ['new-employee','production','manager','owner-admin'],
    level: 'Core',
    minutes: 25,
    safeMode: 'read-only-first',
    summary: 'Learn how to read a pull sheet and what each production action means.',
    outcome: 'The employee can identify the exact blank, source bin, shortage state, and the difference between pulling, producing, and completing/deducting.',
    steps: [
      step('Open Pull Sheets', 'Choose a training order or an order assigned by a manager.', { route: '/pullsheets' }),
      step('Read the line before touching inventory', 'Confirm product/SKU, Brand, Style, Color, Size, quantity, and source bin.' }),
      step('Check for Pending Stock or shortage', 'If the line points to Pending Stock or shows insufficient availability, do not substitute another garment without approval.' }),
      step('Physically pull from the recorded bin', 'Match the garment label to the pull sheet before removing it.' }),
      step('Do not complete early', 'Complete + Deduct should happen only when the blank has actually been consumed for production.', { warning: 'Completing early makes inventory inaccurate and can create false purchasing demand.' }),
      step('Escalate wrong products', 'If the pull sheet requests the wrong blank, stop and use mapping repair or ask a manager. Do not compensate by changing inventory quantities.' }),
    ],
  },
  {
    id: 'production-201',
    title: 'Production 201: From Pulled Blank to QC and Completion',
    roles: ['production','manager','owner-admin'],
    level: 'Intermediate',
    minutes: 35,
    safeMode: 'supervised-live',
    summary: 'Follow the production sequence without losing traceability.',
    outcome: 'The employee can move a job through production, record spoilage, complete/deduct correctly, and use QC.',
    steps: [
      step('Review priority', 'Use Production Board and Order Risk to confirm which job should be worked next.', { route: '/production-board' }),
      step('Confirm artwork is ready', 'Verify approved artwork and production instructions before pressing anything.' }),
      step('Produce the item', 'Follow placement, decoration size, name/number, and artwork instructions exactly.' }),
      step('Record spoilage immediately', 'If a blank is ruined or misprinted, use Spoilage / Misprints instead of silently grabbing another blank.', { route: '/spoilage' }),
      step('Complete and deduct', 'Only after the blank has been used for the job, complete the line and deduct the inventory.' }),
      step('Perform QC', 'Use the QC Checklist and photo proof workflow where required.', { route: '/qc-checklist' }),
      step('Confirm final status', 'Verify the job/line no longer shows open production work and the inventory movement is correct.' }),
    ],
  },
  {
    id: 'purchasing-101',
    title: 'Purchasing 101: Understand What the Report Is Asking You to Buy',
    roles: ['manager','owner-admin'],
    level: 'Core',
    minutes: 30,
    safeMode: 'read-only-first',
    summary: 'Learn how reservations, on-hand stock, Pending Stock, and non-inventory rules affect purchasing.',
    outcome: 'The employee can explain why an item appears on the purchasing report before creating a purchase order.',
    steps: [
      step('Open Purchasing Report', 'Review shortage lines without ordering anything yet.', { route: '/purchasing' }),
      step('Trace the demand source', 'Identify which pull sheet/client/manual order created the need.' }),
      step('Check On Hand and Reserved', 'Confirm the shortage is real rather than caused by a wrong pairing or missing receipt.' }),
      step('Check non-inventory status', 'Fees, services, and customer-supplied items should not generate blank purchasing demand.' }),
      step('Create or update a PO only after validation', 'Order the exact Brand + Style + Color + Size required.' }),
      step('Use Waiting On after ordering', 'Track expected arrivals and late supplier items.', { route: '/waiting-on' }),
    ],
  },
  {
    id: 'client-orders-101',
    title: 'Client Orders 101: Review, Price, Approve, and Convert',
    roles: ['artwork','manager','owner-admin'],
    level: 'Core',
    minutes: 35,
    safeMode: 'simulated-supported',
    summary: 'Practice the online client/team order workflow from submission through production conversion.',
    outcome: 'The employee can map products, enter pricing, create a QBO handoff, record approval/payment, and understand when production demand is created.',
    steps: [
      step('Enable Testing Mode first', 'Turn on Testing Mode and Simulate Supported Writes before training on Client Orders.', { route: '/testing-mode', verify: 'The page reports Testing Mode: Simulated Writes.' }),
      step('Open Client Orders', 'Select a submitted client request and review the customer-entered personalization carefully.', { route: '/client-orders' }),
      step('Map each requested item', 'Choose the exact blank product. Do not use a near match simply because it is available.' }),
      step('Price every line', 'Enter the sell price or apply an approved pricing rule.' }),
      step('Review invoice details', 'Verify garment color, size, name on back, name text color, jersey/employee number, quantity, and line notes.' }),
      step('Practice quote/approval/payment gates', 'In simulated mode, walk through quote sent, customer approval, and payment steps.' }),
      step('Simulate conversion', 'Use Simulate Production Conversion and inspect the preview. Confirm that no production records were written.' }),
    ],
    coachNotes: ['This is the safest full workflow for a new admin employee because supported writes are simulated.', 'Do not assume other application pages are non-mutating just because Testing Mode is enabled.'],
  },
  {
    id: 'manual-orders-101',
    title: 'Manual Invoice Orders 101: Build an Order That Bypasses WooCommerce',
    roles: ['manager','owner-admin','artwork'],
    level: 'Intermediate',
    minutes: 35,
    safeMode: 'supervised-live',
    summary: 'Create and understand a manual invoiced order used for QuickBooks/email/phone orders.',
    outcome: 'The employee can enter a production-ready manual order and understand how it creates a job and inventory demand.',
    steps: [
      step('Open Manual Invoiced Orders', 'Review the customer header and line-item structure before creating anything.', { route: '/manual-orders' }),
      step('Enter customer and invoice reference', 'Use the real QuickBooks/external invoice number when available.' }),
      step('Add exact line items', 'Use one line per exact blank variation and preserve customer personalization in line details.' }),
      step('Verify client details', 'Confirm recipient, garment color, size, name/number, personalization color, placement, artwork note, and quantity.' }),
      step('Understand Generate Job', 'Generating the job creates operational production work and can create reservations/purchasing demand.', { warning: 'Do not generate a job for a test order on production unless explicitly directed.' }),
      step('Verify after creation', 'Open the generated pull sheet and confirm the item identity and quantities are correct.' }),
    ],
  },
  {
    id: 'artwork-101',
    title: 'Artwork 101: Requests, Mockups, Approval, and Production Handoff',
    roles: ['artwork','manager','owner-admin'],
    level: 'Core',
    minutes: 40,
    safeMode: 'read-only-first',
    summary: 'Understand where artwork comes from, how mockups are reviewed, and what “approved” means for production.',
    outcome: 'The employee can locate artwork, review a request, identify the selected/approved mockup, and avoid replacing a downstream production file incorrectly.',
    steps: [
      step('Open Artwork Requests', 'Review a real or training request and identify customer requirements and uploaded files.', { route: '/artwork-requests' }),
      step('Open Mockup Studio', 'Locate the related project and identify originals, prepared artwork, mockups, and production files.', { route: '/mockup-studio' }),
      step('Distinguish selected from approved', 'A selected mockup is not automatically production approved.' }),
      step('Protect downstream files', 'When a file is already referenced by production or a completed request, create a new version instead of replacing history.' }),
      step('Confirm production readiness', 'Before production starts, verify artwork, garment, placement, size, and customer approval.' }),
    ],
  },
  {
    id: 'inventory-audit-101',
    title: 'Inventory Audit 101: Fix Counts Without Hiding the Cause',
    roles: ['warehouse','manager','owner-admin'],
    level: 'Core',
    minutes: 25,
    safeMode: 'supervised-live',
    summary: 'Learn how to reconcile physical inventory while preserving an audit trail.',
    outcome: 'The employee can count a bin, research a variance, and apply a verified adjustment using the correct workflow.',
    steps: [
      step('Choose a small bin', 'Start with one bin and count every unit physically present.', { route: '/inventory-audit' }),
      step('Compare to expected', 'Record the physical count without first changing system quantities.' }),
      step('Investigate meaningful variances', 'Review recent receiving, transfers, production deductions, and spoilage.' }),
      step('Apply only a verified adjustment', 'Use the audit workflow so the difference creates an inventory movement record.' }),
      step('Look for process patterns', 'Repeated shortages in one bin/style usually indicate a workflow problem that should be corrected.' }),
    ],
  },
  {
    id: 'troubleshooting-101',
    title: 'Troubleshooting 101: Stop, Verify, Then Repair',
    roles: ['new-employee','warehouse','production','artwork','manager','owner-admin'],
    level: 'Required',
    minutes: 20,
    safeMode: 'read-only',
    summary: 'A standard response to wrong quantities, wrong products, missing records, timeouts, and unexpected errors.',
    outcome: 'The employee knows when to stop and gather evidence instead of clicking repeatedly or “fixing” data blindly.',
    steps: [
      step('Stop repeating the action', 'If an action errors or times out, do not click it several more times.' }),
      step('Write down the exact symptom', 'Capture the order/pull sheet/PO number, product SKU, quantity, error message, and time.' }),
      step('Verify the resulting state', 'Check the destination screen, inventory movement, order, job, or receipt to determine whether the first action actually completed.' }),
      step('Use the Exception / Integrity tools', 'Check Exception Center, Product Integrity, Operations Integrity, or Deployment Health as appropriate.', { route: '/exception-center' }),
      step('Escalate with evidence', 'Give the manager the exact record number and screenshot rather than only saying “it did not work.”' }),
    ],
  },
  {
    id: 'manager-opening-closing',
    title: 'Manager Daily Opening and Closing Routine',
    roles: ['manager','owner-admin'],
    level: 'Required',
    minutes: 20,
    safeMode: 'read-only',
    summary: 'A repeatable daily control routine for catching problems before they affect customer deadlines.',
    outcome: 'The manager can identify today’s highest-risk work and leave the system in a clean state at close.',
    steps: [
      step('Morning command check', 'Review Daily Command Center and Exception Center.', { route: '/command-center' }),
      step('Review due work', 'Check Order Risk, Production Board, and Pull Sheet Due Dates.' }),
      step('Review incoming stock', 'Check Waiting On and open Purchase Orders.' }),
      step('Assign priorities', 'Confirm which production jobs and receiving tasks staff should work first.' }),
      step('Closing check', 'Review unfinished jobs, unresolved exceptions, incomplete receiving, spoilage, and unusual inventory movements.' }),
    ],
  },
  {
    id: 'admin-advanced',
    title: 'Owner/Admin Advanced: Mapping, Integrity, and Deployment',
    roles: ['owner-admin'],
    level: 'Advanced',
    minutes: 45,
    safeMode: 'read-only-first',
    summary: 'Understand the high-impact tools that should not be delegated until core workflows are mastered.',
    outcome: 'The admin can identify when a problem belongs to product mapping, data integrity, Woo sync, environment health, or application deployment.',
    steps: [
      step('Review Product-to-Blank Mappings', 'Understand that mappings determine which physical blank a source product consumes.', { route: '/product-blank-mappings' }),
      step('Review Product Integrity', 'Use duplicate SKU/barcode/identity diagnostics before editing product identity.', { route: '/product-integrity' }),
      step('Review Operations Integrity', 'Use guarded repair tools for operational inconsistencies.', { route: '/operations-integrity' }),
      step('Review WooCommerce Sync', 'Know how products/variations flow from WooCommerce into operational data.', { route: '/woo-sync' }),
      step('Review Deployment Health', 'Check environment/configuration health before assuming a workflow bug is data-related.', { route: '/deployment-health' }),
      step('Know the change-control rule', 'High-impact repairs, migrations, or bulk changes should be tested, documented, and verified before production use.' }),
    ],
  },
];

export function tutorialsForRole(roleId) {
  return trainingTutorials.filter((tutorial) => tutorial.roles.includes(roleId));
}

export function trainingTutorialSearchText(tutorial) {
  return [
    tutorial.title,
    tutorial.level,
    tutorial.summary,
    tutorial.outcome,
    tutorial.safeMode,
    ...(tutorial.roles || []),
    ...(tutorial.coachNotes || []),
    ...(tutorial.steps || []).flatMap((item) => [item.title, item.instruction, item.verify, item.warning, item.route]),
  ].filter(Boolean).join(' ').toLowerCase();
}
