import { useEffect, useState } from 'react';
import { getPhase5ArtworkRequests, savePhase5ArtworkRequest } from './lib/inventoryApi';

export default function ArtworkRequests() {
  const [rows, setRows] = useState([]); const [status, setStatus] = useState('open'); const [message, setMessage] = useState('');
  const [form, setForm] = useState({ customerName:'', requestTitle:'', requestDetails:'', desiredEmotion:'', preferredShape:'', deadline:'', aiPrompt:'', status:'new', notes:'' });
  async function load(){ try{ setRows(await getPhase5ArtworkRequests(status)); setMessage(''); }catch(err){ setMessage(err.message || 'Failed to load artwork requests.'); } }
  useEffect(()=>{ load(); }, [status]);
  function generatePrompt(){ const prompt = `Create a custom apparel artwork concept for ${form.customerName || 'the customer'}. Request: ${form.requestDetails}. Desired emotion: ${form.desiredEmotion || 'professional and memorable'}. Preferred shape: ${form.preferredShape || 'flexible'}. Include guidance for logo style, colors, layout, print placement, and production notes.`; setForm({...form, aiPrompt: prompt}); }
  async function save(e){ e.preventDefault(); try{ await savePhase5ArtworkRequest(form); setForm({ customerName:'', requestTitle:'', requestDetails:'', desiredEmotion:'', preferredShape:'', deadline:'', aiPrompt:'', status:'new', notes:'' }); await load(); }catch(err){ setMessage(err.message || 'Failed to save artwork request.'); } }
  return <main className="page"><section className="page-header"><div><p className="eyebrow">Artwork</p><h1>AI Artwork Request Integration</h1><p>Create, track, and prompt artwork/design requests linked to customers and jobs.</p></div></section>{message&&<p className="message">{message}</p>}<section className="content-two-column wide-two-column"><form className="card elevated-card" onSubmit={save}><h2>New Artwork Request</h2><label>Customer</label><input value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/><label>Title</label><input value={form.requestTitle} onChange={e=>setForm({...form,requestTitle:e.target.value})}/><label>Request Details</label><textarea value={form.requestDetails} onChange={e=>setForm({...form,requestDetails:e.target.value})}/><label>Emotion</label><input value={form.desiredEmotion} onChange={e=>setForm({...form,desiredEmotion:e.target.value})} placeholder="Energetic, classic, playful..."/><label>Preferred Shape</label><input value={form.preferredShape} onChange={e=>setForm({...form,preferredShape:e.target.value})} placeholder="Circle, badge, horizontal..."/><label>Deadline</label><input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/><button type="button" className="secondary-button" onClick={generatePrompt}>Generate AI Prompt</button><label>AI Prompt</label><textarea value={form.aiPrompt} onChange={e=>setForm({...form,aiPrompt:e.target.value})}/><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="new">New</option><option value="prompt_ready">Prompt Ready</option><option value="in_design">In Design</option><option value="sent_for_approval">Sent for Approval</option><option value="revision_requested">Revision Requested</option><option value="approved">Approved</option></select><label>Notes</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button>Save Request</button></form><section className="card elevated-card table-card"><div className="section-heading-row"><h2>Requests</h2><select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Open</option><option value="approved">Approved</option><option value="all">All</option></select></div><div className="responsive-table"><table className="data-table"><thead><tr><th>Request</th><th>Customer</th><th>Status</th><th>Deadline</th><th>Prompt</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan="5">No artwork requests.</td></tr>:rows.map(row=><tr key={row.id}><td>{row.request_title || 'Untitled'}<br/><small>{row.request_details}</small></td><td>{row.customer_name}</td><td>{row.status}</td><td>{row.deadline || '—'}</td><td><small>{row.ai_prompt}</small></td></tr>)}</tbody></table></div></section></section></main>;
}
