import { useEffect, useState } from 'react';
import { getPhase5Employees, getPhase5Tasks, savePhase5Employee, savePhase5Task } from './lib/inventoryApi';

const TASK_TYPES = ['pull_blanks', 'print_transfers', 'press_garments', 'qc', 'pack_order', 'receive_shipment', 'count_bin', 'reprint', 'artwork', 'general'];
const STATUSES = ['not_started', 'in_progress', 'blocked', 'completed'];

export default function EmployeeTasks() {
  const [employees, setEmployees] = useState([]);
  const [tasks, setTasks] = useState([]);
  const [filter, setFilter] = useState('open');
  const [message, setMessage] = useState('');
  const [employee, setEmployee] = useState({ name: '', role: '', hourlyCost: 0 });
  const [task, setTask] = useState({ title: '', taskType: 'general', assignedToEmployeeId: '', priority: 0, dueAt: '', notes: '' });

  async function load() { try { const [e,t]=await Promise.all([getPhase5Employees(), getPhase5Tasks(filter)]); setEmployees(e); setTasks(t); setMessage(''); } catch(err){ setMessage(err.message || 'Failed to load tasks.'); } }
  useEffect(()=>{ load(); }, [filter]);
  async function addEmployee(e){ e.preventDefault(); try { await savePhase5Employee(employee); setEmployee({ name:'', role:'', hourlyCost:0 }); await load(); } catch(err){ setMessage(err.message || 'Failed to save employee.'); } }
  async function addTask(e){ e.preventDefault(); try { await savePhase5Task(task); setTask({ title:'', taskType:'general', assignedToEmployeeId:'', priority:0, dueAt:'', notes:'' }); await load(); } catch(err){ setMessage(err.message || 'Failed to save task.'); } }
  async function updateStatus(id, status){ try { await savePhase5Task({ id, title: tasks.find(t=>t.id===id)?.title, taskType: tasks.find(t=>t.id===id)?.task_type, assignedToEmployeeId: tasks.find(t=>t.id===id)?.assigned_to_employee_id, priority: tasks.find(t=>t.id===id)?.priority, dueAt: tasks.find(t=>t.id===id)?.due_at, notes: tasks.find(t=>t.id===id)?.notes, status }); await load(); } catch(err){ setMessage(err.message || 'Failed to update task.'); } }

  return <main className="page"><section className="page-header"><div><p className="eyebrow">Team</p><h1>Employee Task Assignment</h1><p>Assign shop-floor tasks for pulling, printing, pressing, QC, receiving, counting, artwork, and remakes.</p></div></section>{message&&<p className="message">{message}</p>}<section className="content-two-column wide-two-column"><form onSubmit={addTask} className="card elevated-card"><h2>Create Task</h2><label>Title</label><input value={task.title} onChange={e=>setTask({...task,title:e.target.value})} placeholder="Pull blanks for order #..."/><label>Task Type</label><select value={task.taskType} onChange={e=>setTask({...task,taskType:e.target.value})}>{TASK_TYPES.map(x=><option key={x} value={x}>{x}</option>)}</select><label>Assign To</label><select value={task.assignedToEmployeeId} onChange={e=>setTask({...task,assignedToEmployeeId:e.target.value})}><option value="">Unassigned</option>{employees.map(emp=><option key={emp.id} value={emp.id}>{emp.name}</option>)}</select><label>Priority</label><input type="number" value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}/><label>Due</label><input type="datetime-local" value={task.dueAt} onChange={e=>setTask({...task,dueAt:e.target.value})}/><label>Notes</label><textarea value={task.notes} onChange={e=>setTask({...task,notes:e.target.value})}/><button>Create Task</button></form><form onSubmit={addEmployee} className="card elevated-card"><h2>Add Employee</h2><label>Name</label><input value={employee.name} onChange={e=>setEmployee({...employee,name:e.target.value})}/><label>Role</label><input value={employee.role} onChange={e=>setEmployee({...employee,role:e.target.value})} placeholder="Production, QC, Receiving..."/><label>Hourly Cost</label><input type="number" step="0.01" value={employee.hourlyCost} onChange={e=>setEmployee({...employee,hourlyCost:e.target.value})}/><button>Add Employee</button></form></section><section className="card elevated-card table-card"><div className="section-heading-row"><h2>Tasks</h2><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open</option><option value="completed">Completed</option><option value="all">All</option></select></div><div className="responsive-table"><table className="data-table"><thead><tr><th>Task</th><th>Job</th><th>Assigned</th><th>Priority</th><th>Due</th><th>Status</th></tr></thead><tbody>{tasks.length===0?<tr><td colSpan="6">No tasks.</td></tr>:tasks.map(t=><tr key={t.id}><td><strong>{t.title}</strong><br/><small>{t.task_type}</small></td><td>{t.job_name || '—'}</td><td>{t.assigned_to_name || 'Unassigned'}</td><td>{t.priority}</td><td>{t.due_at?new Date(t.due_at).toLocaleString():'—'}</td><td><select value={t.status} onChange={e=>updateStatus(t.id,e.target.value)}>{STATUSES.map(s=><option key={s} value={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div></section></main>;
}
