import { useEffect, useState } from 'react';
import { addInventoryAuditCount, closeInventoryAuditSession, createInventoryAuditSession, getInventoryAuditCounts, getInventoryAuditSessions } from './lib/phase6Api';

export default function InventoryAudit() {
  const [sessions,setSessions]=useState([]); const [active,setActive]=useState(null); const [counts,setCounts]=useState([]); const [error,setError]=useState('');
  const [sessionForm,setSessionForm]=useState({started_by:'',bin_code:'',audit_type:'cycle_count',notes:''});
  const [countForm,setCountForm]=useState({sku:'',product_name:'',expected_quantity:'',counted_quantity:'',adjustment_reason:'',counted_by:'',notes:''});
  async function load(){ setError(''); try{ setSessions(await getInventoryAuditSessions()); if(active) setCounts(await getInventoryAuditCounts(active.id)); }catch(e){setError(e.message);} }
  useEffect(()=>{load();},[]);
  async function createSession(e){e.preventDefault(); const s=await createInventoryAuditSession(sessionForm); setActive(s); setSessionForm({started_by:'',bin_code:'',audit_type:'cycle_count',notes:''}); setSessions(await getInventoryAuditSessions());}
  async function selectSession(s){setActive(s); setCounts(await getInventoryAuditCounts(s.id));}
  async function addCount(e){e.preventDefault(); await addInventoryAuditCount({...countForm, session_id:active.id}); setCountForm({sku:'',product_name:'',expected_quantity:'',counted_quantity:'',adjustment_reason:'',counted_by:'',notes:''}); setCounts(await getInventoryAuditCounts(active.id));}
  async function close(){ await closeInventoryAuditSession(active.id, prompt('Completed by:', '')||''); setActive(null); setCounts([]); await load(); }
  return <main className="page phase6-page"><h1>Inventory Audit / Cycle Count</h1><p className="muted">Count bins, record variances, and preserve an audit trail before making adjustments.</p>{error&&<div className="error-card">{error}</div>}
    <section className="phase6-two-column"><form className="phase6-panel" onSubmit={createSession}><h2>Start Audit</h2><input placeholder="Started by" value={sessionForm.started_by} onChange={e=>setSessionForm({...sessionForm,started_by:e.target.value})}/><input placeholder="Bin code" value={sessionForm.bin_code} onChange={e=>setSessionForm({...sessionForm,bin_code:e.target.value})}/><select value={sessionForm.audit_type} onChange={e=>setSessionForm({...sessionForm,audit_type:e.target.value})}><option>cycle_count</option><option>full_bin_audit</option><option>spot_check</option></select><textarea placeholder="Notes" value={sessionForm.notes} onChange={e=>setSessionForm({...sessionForm,notes:e.target.value})}/><button className="button button-primary">Start Session</button></form>
      <div className="phase6-panel"><h2>Open Sessions</h2>{sessions.map(s=><button key={s.id} className={`phase6-list-button ${active?.id===s.id?'active':''}`} onClick={()=>selectSession(s)}>{s.bin_code||'No bin'} — {s.status} — {new Date(s.created_at).toLocaleDateString()}</button>)}</div></section>
    {active&&<section className="phase6-panel"><div className="page-header-row"><h2>Counting: {active.bin_code}</h2><button className="button" onClick={close}>Close Session</button></div><form className="phase6-grid-form" onSubmit={addCount}><input placeholder="SKU" value={countForm.sku} onChange={e=>setCountForm({...countForm,sku:e.target.value})}/><input placeholder="Product name" value={countForm.product_name} onChange={e=>setCountForm({...countForm,product_name:e.target.value})}/><input type="number" placeholder="Expected qty" value={countForm.expected_quantity} onChange={e=>setCountForm({...countForm,expected_quantity:e.target.value})}/><input type="number" placeholder="Counted qty" value={countForm.counted_quantity} onChange={e=>setCountForm({...countForm,counted_quantity:e.target.value})} required/><input placeholder="Counted by" value={countForm.counted_by} onChange={e=>setCountForm({...countForm,counted_by:e.target.value})}/><input placeholder="Reason" value={countForm.adjustment_reason} onChange={e=>setCountForm({...countForm,adjustment_reason:e.target.value})}/><button className="button button-primary">Add Count</button></form>
      <div className="table-wrap"><table className="data-table compact-table"><thead><tr><th>SKU</th><th>Name</th><th>Expected</th><th>Counted</th><th>Variance</th><th>Reason</th></tr></thead><tbody>{counts.map(c=><tr key={c.id}><td>{c.sku}</td><td>{c.product_name}</td><td>{c.expected_quantity}</td><td>{c.counted_quantity}</td><td className={c.variance_quantity!==0?'text-danger':''}>{c.variance_quantity}</td><td>{c.adjustment_reason}</td></tr>)}</tbody></table></div></section>}
  </main>;
}
