import { useEffect, useMemo, useState } from 'react';
import { completeOnsiteItem, getOnsiteCategories, getOnsiteCategoryMenu, getOnsiteInventoryV2 } from './lib/onsiteSalesApi';
import skilledCraftingLogo from './assets/logo.png';
import './OnsiteSales.css';

const UNCLASSIFIED = '__unclassified__';
const EMPTY_SELECTION = { item_type_id: '', brand_id: '', style_id: '', color_id: '', size_id: '' };
const DEVICE_MODES = [['phone','Phone'],['tablet','Tablet'],['laptop','Laptop']];
function labelInventory(row) { return [row.item_type, row.brand, row.style, row.color, row.size].filter(Boolean).join(' • '); }
function itemKey(row) { return row.item_type_id == null ? UNCLASSIFIED : String(row.item_type_id); }
function matches(row, selection, through = 'size_id') { const order=['item_type_id','brand_id','style_id','color_id','size_id']; for (const field of order) { if (!selection[field]) return true; const rv=field==='item_type_id'?itemKey(row):String(row[field]??''); if(rv!==String(selection[field])) return false; if(field===through) break; } return true; }
function uniqueOptions(rows,idField,labelField,customId){const map=new Map(); rows.forEach((row)=>{const id=customId?customId(row):row[idField]; const label=row[labelField]; if(id==null||!label)return; const key=String(id); if(!map.has(key))map.set(key,{id:key,label:String(label)});}); return [...map.values()].sort((a,b)=>a.label.localeCompare(b.label,undefined,{numeric:true}));}
function Selector({label,value,options,placeholder,disabled,onChange}){return <label>{label}<select value={value} disabled={disabled} onChange={(e)=>onChange(e.target.value)}><option value="">{placeholder}</option>{options.map((row)=><option key={row.id} value={row.id}>{row.label}</option>)}</select></label>;}

export default function OnsiteSales(){
 const [categories,setCategories]=useState([]);
 const [categoryId,setCategoryId]=useState(()=>localStorage.getItem('sc-onsite-category')||'');
 const [categoryMenu,setCategoryMenu]=useState({logos:[],products:[]});
 const [inventory,setInventory]=useState([]); const [selection,setSelection]=useState(EMPTY_SELECTION);
 const [form,setForm]=useState({blank_product_id:'',customer_name:'',player_name:'',player_number:'',personalization_color:'White',logo_name:'',woo_product_id:'',woo_variation_id:'',label_size:'4x6',notes:''});
 const [testMode,setTestMode]=useState(()=>localStorage.getItem('sc-onsite-test-mode')==='1');
 const [deviceMode,setDeviceMode]=useState(()=>localStorage.getItem('sc-onsite-device-mode')||'laptop');
 const [result,setResult]=useState(null); const [message,setMessage]=useState(''); const [working,setWorking]=useState(false);
 useEffect(()=>{getOnsiteCategories().then(setCategories).catch((e)=>setMessage(e.message));},[]);
 useEffect(()=>{if(!categoryId){setCategoryMenu({logos:[],products:[]});return;} localStorage.setItem('sc-onsite-category',categoryId); getOnsiteCategoryMenu(categoryId).then(setCategoryMenu).catch((e)=>setMessage(e.message));},[categoryId]);
 useEffect(()=>{getOnsiteInventoryV2('').then(setInventory).catch((e)=>setMessage(e.message));},[result]);
 useEffect(()=>{localStorage.setItem('sc-onsite-test-mode',testMode?'1':'0');},[testMode]);
 useEffect(()=>{localStorage.setItem('sc-onsite-device-mode',deviceMode);},[deviceMode]);
 const typeOptions=useMemo(()=>uniqueOptions(inventory,'item_type_id','item_type',itemKey),[inventory]); const afterType=useMemo(()=>inventory.filter((r)=>matches(r,selection,'item_type_id')),[inventory,selection]);
 const brandOptions=useMemo(()=>uniqueOptions(afterType,'brand_id','brand'),[afterType]); const afterBrand=useMemo(()=>afterType.filter((r)=>!selection.brand_id||String(r.brand_id)===selection.brand_id),[afterType,selection.brand_id]);
 const styleOptions=useMemo(()=>uniqueOptions(afterBrand,'style_id','style'),[afterBrand]); const afterStyle=useMemo(()=>afterBrand.filter((r)=>!selection.style_id||String(r.style_id)===selection.style_id),[afterBrand,selection.style_id]);
 const colorOptions=useMemo(()=>uniqueOptions(afterStyle,'color_id','color'),[afterStyle]); const afterColor=useMemo(()=>afterStyle.filter((r)=>!selection.color_id||String(r.color_id)===selection.color_id),[afterStyle,selection.color_id]);
 const sizeOptions=useMemo(()=>uniqueOptions(afterColor,'size_id','size'),[afterColor]); const exactRows=useMemo(()=>afterColor.filter((r)=>selection.size_id&&String(r.size_id)===selection.size_id),[afterColor,selection.size_id]);
 const selectedBlank=useMemo(()=>inventory.find((r)=>String(r.blank_product_id)===String(form.blank_product_id)),[form.blank_product_id,inventory]);
 function update(name,value){setForm((c)=>({...c,[name]:value}));setResult(null);setMessage('');}
 function selectDimension(field,value){const order=['item_type_id','brand_id','style_id','color_id','size_id'];const index=order.indexOf(field);const next={...selection,[field]:value};order.slice(index+1).forEach((n)=>{next[n]='';});setSelection(next);setForm((c)=>({...c,blank_product_id:''}));setResult(null);setMessage('');if(field==='size_id'&&value){const candidates=inventory.filter((r)=>itemKey(r)===next.item_type_id&&String(r.brand_id??'')===next.brand_id&&String(r.style_id??'')===next.style_id&&String(r.color_id??'')===next.color_id&&String(r.size_id??'')===value);if(candidates.length===1)setForm((c)=>({...c,blank_product_id:candidates[0].blank_product_id}));else if(candidates.length>1)setMessage('More than one active blank record matches this exact selection. Resolve the duplicate in Product Integrity before selling it.');}}
 function changeCategory(value){setCategoryId(value);setCategoryMenu({logos:[],products:[]});setForm((c)=>({...c,logo_name:'',woo_product_id:'',woo_variation_id:''}));setResult(null);setMessage('');}
 function changeLogo(value){const row=categoryMenu.logos.find((e)=>e.name===value);setForm((c)=>({...c,logo_name:value,woo_product_id:row?.product_ids?.length===1?String(row.product_ids[0]):'',woo_variation_id:''}));setResult(null);setMessage('');}
 async function submit(event){event.preventDefault();if(!categoryId){setMessage('Choose the active WooCommerce category.');return;}if(!form.blank_product_id||!selectedBlank){setMessage('Choose Type, Brand, Style, Color, and Size for an in-stock blank.');return;} const verb=testMode?'Create a TEST label without deducting inventory':'Deduct one item and create its production label';if(!window.confirm(`${verb} for ${labelInventory(selectedBlank)}?`))return;setWorking(true);setMessage(testMode?'Creating test label — inventory will not change…':'Deducting inventory and creating label…');try{const completed=await completeOnsiteItem({...form,woo_category_id:categoryId,test_mode:testMode});setResult(completed);setMessage(testMode?'TEST complete. No inventory or production record was changed. Print and inspect the test label.':'Item recorded and inventory deducted. Print the label now.');setSelection(EMPTY_SELECTION);setForm((c)=>({...c,blank_product_id:'',customer_name:'',player_name:'',player_number:'',notes:''}));}catch(e){setMessage(e.message);}finally{setWorking(false);}}
 return <main className={`page onsite-page onsite-device-${deviceMode}`}>
  <section className="page-header no-print"><div><p className="eyebrow">Mobile production counter</p><h1>On-site Sales</h1><p>Set the event category, choose its graphic, then drill into only physical blanks that are actually available.</p></div></section>
  <section className="onsite-controlbar no-print"><label className={`onsite-test-toggle ${testMode?'is-active':''}`}><input type="checkbox" checked={testMode} onChange={(e)=>{setTestMode(e.target.checked);setResult(null);setMessage(e.target.checked?'TEST MODE enabled. No inventory or production records will be changed.':'Live mode restored. Completed items will deduct inventory.');}}/><span><strong>Test mode</strong><small>{testMode?'No inventory deduction / no production record':'Live inventory deduction'}</small></span></label><div className="onsite-device-toggle" role="group" aria-label="On-site page preview size">{DEVICE_MODES.map(([key,label])=><button key={key} type="button" className={deviceMode===key?'is-active':''} onClick={()=>setDeviceMode(key)}>{label}</button>)}</div></section>
  {testMode&&<div className="onsite-test-banner no-print">TEST MODE — labels are printable, but inventory and production history are not changed.</div>}
  {message&&<p className="message no-print" role="status">{message}</p>}
  <div className="onsite-device-shell no-print"><form onSubmit={submit} className="onsite-layout">
   <section className="card onsite-step onsite-event"><h2>1. Event & graphic</h2><label>Active WooCommerce category<select value={categoryId} onChange={(e)=>changeCategory(e.target.value)}><option value="">Choose category</option>{categories.map((r)=><option key={r.id} value={r.id}>{r.name} ({r.count})</option>)}</select></label><label>Logo / graphic<select value={form.logo_name} disabled={!categoryId} onChange={(e)=>changeLogo(e.target.value)}><option value="">No logo selected</option>{categoryMenu.logos.map((r)=><option key={r.name} value={r.name}>{r.name}</option>)}</select></label>{categoryId&&!categoryMenu.logos.length?<p className="onsite-help">No Logo/Graphic/Design attribute options were found on published products in this category.</p>:null}</section>
   <section className="card onsite-step onsite-blank"><h2>2. Physical blank</h2><p className="onsite-help">Each choice narrows the next list to blanks with positive availability after reservations.</p><div className="onsite-cascade"><Selector label="Type" value={selection.item_type_id} options={typeOptions} placeholder="Choose type" onChange={(v)=>selectDimension('item_type_id',v)}/><Selector label="Brand" value={selection.brand_id} options={brandOptions} placeholder="Choose brand" disabled={!selection.item_type_id} onChange={(v)=>selectDimension('brand_id',v)}/><Selector label="Style" value={selection.style_id} options={styleOptions} placeholder="Choose style" disabled={!selection.brand_id} onChange={(v)=>selectDimension('style_id',v)}/><Selector label="Color" value={selection.color_id} options={colorOptions} placeholder="Choose color" disabled={!selection.style_id} onChange={(v)=>selectDimension('color_id',v)}/><Selector label="Size" value={selection.size_id} options={sizeOptions} placeholder="Choose size" disabled={!selection.color_id} onChange={(v)=>selectDimension('size_id',v)}/></div>{selectedBlank?<div className="onsite-selected-blank"><strong>{labelInventory(selectedBlank)}</strong><span>{selectedBlank.available_quantity} available</span><small>{selectedBlank.sku_base}</small></div>:selection.size_id&&!exactRows.length?<p className="onsite-warning">That selection no longer has available inventory. Refresh or choose another size.</p>:null}</section>
   <section className="card onsite-step"><h2>3. Customer & production</h2><div className="onsite-fields"><label>Customer name<input value={form.customer_name} onChange={(e)=>update('customer_name',e.target.value)}/></label><label>Player name<input value={form.player_name} onChange={(e)=>update('player_name',e.target.value)}/></label><label>Player number<input value={form.player_number} onChange={(e)=>update('player_number',e.target.value)} inputMode="numeric"/></label><label>Name / number color<input value={form.personalization_color} onChange={(e)=>update('personalization_color',e.target.value)}/></label><label>Label size<select value={form.label_size} onChange={(e)=>update('label_size',e.target.value)}><option value="2x3">2 × 3 inches</option><option value="4x6">4 × 6 inches</option></select></label><label className="wide">Production notes<textarea value={form.notes} onChange={(e)=>update('notes',e.target.value)}/></label></div><button className="primary-action onsite-complete" disabled={working||!form.blank_product_id}>{working?'Recording…':testMode?'Create TEST label':'Complete item & create label'}</button></section>
  </form></div>
  {result&&<section className={`onsite-label label-${result.label_size||form.label_size} ${result.test_mode?'is-test-label':''}`}>{result.test_mode&&<div className="onsite-test-watermark">TEST</div>}<header><img className="onsite-label-logo" src={skilledCraftingLogo} alt="Skilled Crafting"/><span>{new Date(result.produced_at).toLocaleDateString()}</span></header>{result.test_mode&&<strong className="onsite-test-label-note">TEST MODE — NO INVENTORY DEDUCTION</strong>}<h2>{result.customer_name||'On-site customer'}</h2><p>{result.blank_label}</p>{result.logo_name&&<p><strong>Graphic:</strong> {result.logo_name}</p>}{result.player_name&&<p><strong>Player:</strong> {result.player_name}</p>}{result.player_number&&<p><strong>Number:</strong> {result.player_number} · {result.personalization_color||''}</p>}<footer><span>Production #{result.production_number}</span><span>{result.source_bin_label}</span></footer><button type="button" className="no-print primary-action" onClick={()=>window.print()}>Print label</button></section>}
 </main>;
}
