import { useEffect, useState } from 'react';
import { getPhase5PricingRules, savePhase5PricingRule, money } from './lib/inventoryApi';

export default function PricingRules() {
  const [rules, setRules] = useState([]);
  const [form, setForm] = useState({ ruleName:'', productType:'', decorationType:'', markupMultiplier:2.2, decorationCost:6, setupFee:0, minimumMarginPercent:45 });
  const [message, setMessage] = useState('');
  async function load(){ try{ setRules(await getPhase5PricingRules()); setMessage(''); }catch(err){ setMessage(err.message || 'Failed to load pricing rules.'); } }
  useEffect(()=>{ load(); }, []);
  async function save(e){ e.preventDefault(); try{ await savePhase5PricingRule(form); setForm({ ruleName:'', productType:'', decorationType:'', markupMultiplier:2.2, decorationCost:6, setupFee:0, minimumMarginPercent:45 }); await load(); }catch(err){ setMessage(err.message || 'Failed to save rule.'); } }
  return <main className="page"><section className="page-header"><div><p className="eyebrow">Pricing</p><h1>Pricing Rules Engine</h1><p>Maintain markup, decoration cost, setup fees, and minimum margin targets.</p></div></section>{message&&<p className="message">{message}</p>}<section className="content-two-column wide-two-column"><form onSubmit={save} className="card elevated-card"><h2>Add Pricing Rule</h2><label>Rule Name</label><input value={form.ruleName} onChange={e=>setForm({...form,ruleName:e.target.value})}/><label>Product Type</label><input value={form.productType} onChange={e=>setForm({...form,productType:e.target.value})} placeholder="Hoodie, Tee, Hat..."/><label>Decoration Type</label><input value={form.decorationType} onChange={e=>setForm({...form,decorationType:e.target.value})} placeholder="DTF, embroidery, left chest..."/><div className="form-grid"><label>Markup<input type="number" step="0.01" value={form.markupMultiplier} onChange={e=>setForm({...form,markupMultiplier:e.target.value})}/></label><label>Decoration Cost<input type="number" step="0.01" value={form.decorationCost} onChange={e=>setForm({...form,decorationCost:e.target.value})}/></label><label>Setup Fee<input type="number" step="0.01" value={form.setupFee} onChange={e=>setForm({...form,setupFee:e.target.value})}/></label><label>Target Margin %<input type="number" step="0.1" value={form.minimumMarginPercent} onChange={e=>setForm({...form,minimumMarginPercent:e.target.value})}/></label></div><button>Save Rule</button></form><section className="card elevated-card table-card"><h2>Rules</h2><table className="data-table"><thead><tr><th>Rule</th><th>Type</th><th>Markup</th><th>Decoration</th><th>Setup</th><th>Margin</th></tr></thead><tbody>{rules.map(rule=><tr key={rule.id}><td>{rule.rule_name}</td><td>{rule.product_type || 'Any'}<br/><small>{rule.decoration_type || 'Any decoration'}</small></td><td>{rule.markup_multiplier}x</td><td>{money(rule.decoration_cost)}</td><td>{money(rule.setup_fee)}</td><td>{rule.minimum_margin_percent}%</td></tr>)}</tbody></table></section></section></main>;
}
