import { useEffect, useState } from 'react';
import { getPhase5ProductionTimeRules, savePhase5ProductionTimeRule } from './lib/inventoryApi';

export default function ProductionEstimator() {
  const [rules, setRules] = useState([]);
  const [form, setForm] = useState({ ruleName:'DTF Pressing', decorationType:'DTF', setupMinutes:20, secondsPerUnit:60, qcSecondsPerUnit:20, packingSecondsPerUnit:20 });
  const [estimate, setEstimate] = useState({ quantity:48, setupMinutes:20, secondsPerUnit:60, qcSecondsPerUnit:20, packingSecondsPerUnit:20 });
  const [message, setMessage] = useState('');
  async function load(){ try{ setRules(await getPhase5ProductionTimeRules()); setMessage(''); }catch(err){ setMessage(err.message || 'Failed to load estimator.'); } }
  useEffect(()=>{ load(); }, []);
  async function save(e){ e.preventDefault(); try{ await savePhase5ProductionTimeRule(form); await load(); }catch(err){ setMessage(err.message || 'Failed to save rule.'); } }
  const totalMinutes = Number(estimate.setupMinutes||0) + (Number(estimate.quantity||0) * (Number(estimate.secondsPerUnit||0)+Number(estimate.qcSecondsPerUnit||0)+Number(estimate.packingSecondsPerUnit||0)) / 60);
  return <main className="page"><section className="page-header"><div><p className="eyebrow">Scheduling</p><h1>Production Time Estimator</h1><p>Estimate setup, pressing, QC, and packing time for scheduling and rush decisions.</p></div></section>{message&&<p className="message">{message}</p>}<section className="content-two-column wide-two-column"><section className="card elevated-card"><h2>Quick Estimate</h2><div className="form-grid"><label>Quantity<input type="number" value={estimate.quantity} onChange={e=>setEstimate({...estimate,quantity:e.target.value})}/></label><label>Setup Min<input type="number" value={estimate.setupMinutes} onChange={e=>setEstimate({...estimate,setupMinutes:e.target.value})}/></label><label>Press Sec/Unit<input type="number" value={estimate.secondsPerUnit} onChange={e=>setEstimate({...estimate,secondsPerUnit:e.target.value})}/></label><label>QC Sec/Unit<input type="number" value={estimate.qcSecondsPerUnit} onChange={e=>setEstimate({...estimate,qcSecondsPerUnit:e.target.value})}/></label><label>Pack Sec/Unit<input type="number" value={estimate.packingSecondsPerUnit} onChange={e=>setEstimate({...estimate,packingSecondsPerUnit:e.target.value})}/></label></div><div className="hero-stat-card inline-stat"><span className="stat-number">{(totalMinutes/60).toFixed(2)} hrs</span><span className="stat-label">Estimated production time</span></div></section><form className="card elevated-card" onSubmit={save}><h2>Save Time Rule</h2><label>Rule Name</label><input value={form.ruleName} onChange={e=>setForm({...form,ruleName:e.target.value})}/><label>Decoration Type</label><input value={form.decorationType} onChange={e=>setForm({...form,decorationType:e.target.value})}/><div className="form-grid"><label>Setup Min<input type="number" value={form.setupMinutes} onChange={e=>setForm({...form,setupMinutes:e.target.value})}/></label><label>Press Sec<input type="number" value={form.secondsPerUnit} onChange={e=>setForm({...form,secondsPerUnit:e.target.value})}/></label><label>QC Sec<input type="number" value={form.qcSecondsPerUnit} onChange={e=>setForm({...form,qcSecondsPerUnit:e.target.value})}/></label><label>Pack Sec<input type="number" value={form.packingSecondsPerUnit} onChange={e=>setForm({...form,packingSecondsPerUnit:e.target.value})}/></label></div><button>Save Rule</button></form></section><section className="card elevated-card table-card"><h2>Saved Time Rules</h2><div className="responsive-table"><table className="data-table"><thead><tr><th>Rule</th><th>Decoration</th><th>Setup</th><th>Production</th><th>QC</th><th>Packing</th></tr></thead><tbody>{rules.length===0?<tr><td colSpan="6">No time rules yet.</td></tr>:rules.map(rule=><tr key={rule.id}><td>{rule.rule_name}</td><td>{rule.decoration_type || 'Any'}</td><td>{rule.setup_minutes} min</td><td>{rule.seconds_per_unit}s/unit</td><td>{rule.qc_seconds_per_unit}s/unit</td><td>{rule.packing_seconds_per_unit}s/unit</td></tr>)}</tbody></table></div></section></main>;
}
