import { useEffect, useState } from 'react';
import { createPhase5Quote, getPhase5PricingRules, getPhase5Quotes, money } from './lib/inventoryApi';

export default function QuoteBuilder() {
  const [quotes, setQuotes] = useState([]);
  const [rules, setRules] = useState([]);
  const [message, setMessage] = useState('');
  const [form, setForm] = useState({ customerName:'', quoteTitle:'', notes:'' });
  const [item, setItem] = useState({ description:'', quantity:12, blankCost:8, decorationCost:6, laborCost:2, priceEach:24 });
  async function load(){ try{ const [q,r]=await Promise.all([getPhase5Quotes('open'), getPhase5PricingRules()]); setQuotes(q); setRules(r); setMessage(''); } catch(err){ setMessage(err.message || 'Failed to load quotes.'); } }
  useEffect(()=>{ load(); }, []);
  const costEach = Number(item.blankCost||0)+Number(item.decorationCost||0)+Number(item.laborCost||0);
  const profitEach = Number(item.priceEach||0)-costEach;
  const margin = Number(item.priceEach||0)>0 ? (profitEach/Number(item.priceEach||0))*100 : 0;
  async function create(e){ e.preventDefault(); try{ await createPhase5Quote({ ...form, items:[item] }); setForm({customerName:'',quoteTitle:'',notes:''}); await load(); } catch(err){ setMessage(err.message || 'Failed to create quote.'); } }
  return <main className="page"><section className="page-header"><div><p className="eyebrow">Sales + Profit</p><h1>Quote Builder</h1><p>Create quotes with blank cost, decoration cost, labor, sell price, profit, and margin.</p></div></section>{message&&<p className="message">{message}</p>}<section className="content-two-column wide-two-column"><form className="card elevated-card" onSubmit={create}><h2>New Quote</h2><label>Customer</label><input value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/><label>Quote Title</label><input value={form.quoteTitle} onChange={e=>setForm({...form,quoteTitle:e.target.value})}/><label>Item Description</label><input value={item.description} onChange={e=>setItem({...item,description:e.target.value})} placeholder="Gildan 18500 Navy hoodie with left chest logo"/><div className="form-grid"><label>Qty<input type="number" value={item.quantity} onChange={e=>setItem({...item,quantity:e.target.value})}/></label><label>Blank Cost<input type="number" step="0.01" value={item.blankCost} onChange={e=>setItem({...item,blankCost:e.target.value})}/></label><label>Decoration<input type="number" step="0.01" value={item.decorationCost} onChange={e=>setItem({...item,decorationCost:e.target.value})}/></label><label>Labor<input type="number" step="0.01" value={item.laborCost} onChange={e=>setItem({...item,laborCost:e.target.value})}/></label><label>Price Each<input type="number" step="0.01" value={item.priceEach} onChange={e=>setItem({...item,priceEach:e.target.value})}/></label></div><p><strong>Estimated margin:</strong> {margin.toFixed(1)}% · <strong>Profit:</strong> {money(profitEach*Number(item.quantity||0))}</p><label>Notes</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button>Create Quote</button></form><section className="card elevated-card"><h2>Pricing Rules Snapshot</h2>{rules.length===0?<p>No pricing rules yet.</p>:rules.slice(0,8).map(rule=><div key={rule.id} className="compact-row"><strong>{rule.rule_name}</strong><span>{rule.markup_multiplier}x markup · {money(rule.decoration_cost)} decoration · target {rule.minimum_margin_percent}%</span></div>)}</section></section><section className="card elevated-card table-card"><h2>Recent Quotes</h2><div className="responsive-table"><table className="data-table"><thead><tr><th>Quote</th><th>Customer</th><th>Status</th><th>Revenue</th><th>Cost</th><th>Profit</th><th>Margin</th></tr></thead><tbody>{quotes.length===0?<tr><td colSpan="7">No quotes yet.</td></tr>:quotes.map(q=><tr key={q.id}><td>{q.quote_number}<br/><small>{q.quote_title}</small></td><td>{q.customer_name}</td><td>{q.status}</td><td>{money(q.total_revenue)}</td><td>{money(q.total_cost)}</td><td>{money(q.estimated_profit)}</td><td>{Number(q.estimated_margin_percent||0).toFixed(1)}%</td></tr>)}</tbody></table></div></section></main>;
}
