-- Step 7: supplier feed run tracking and private source cache.
-- ADDITIVE ONLY. Existing supplier catalog rows and feed settings are not changed.

begin;
set local lock_timeout = '5s';
set local statement_timeout = '120s';

create table if not exists public.sc_supplier_catalog_sync_runs (
  id bigint generated by default as identity primary key,
  feed_id_text text not null,
  initiated_by uuid,
  status text not null default 'running'
    check (status in ('running', 'completed', 'failed', 'cancelled')),
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  cache_bucket text,
  cache_object_path text,
  source_url text,
  source_label text,
  source_kind text,
  source_etag text,
  source_last_modified text,
  source_sha256 text,
  source_bytes bigint,
  rows_processed bigint not null default 0,
  rows_inserted bigint not null default 0,
  rows_updated bigint not null default 0,
  blank_products_updated bigint not null default 0,
  last_offset bigint not null default 0,
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists sc_supplier_sync_runs_feed_idx
  on public.sc_supplier_catalog_sync_runs (feed_id_text, started_at desc);
create index if not exists sc_supplier_sync_runs_status_idx
  on public.sc_supplier_catalog_sync_runs (status, updated_at desc);

-- Prevent two new active runs for the same feed. This affects only the new run ledger.
create unique index if not exists sc_supplier_sync_one_running_per_feed_uidx
  on public.sc_supplier_catalog_sync_runs (feed_id_text)
  where status = 'running';

alter table public.sc_supplier_catalog_sync_runs enable row level security;
revoke all on public.sc_supplier_catalog_sync_runs from public, anon, authenticated;
grant select, insert, update on public.sc_supplier_catalog_sync_runs to service_role;

comment on table public.sc_supplier_catalog_sync_runs is
  'Service-role ledger for resumable supplier feed imports. Source files are cached privately to avoid repeated supplier downloads.';

-- The cache is service-role only. No browser policy is added.
do $block$
begin
  if to_regclass('storage.buckets') is not null then
    insert into storage.buckets(id, name, public, file_size_limit)
    values ('supplier-sync-cache', 'supplier-sync-cache', false, 104857600)
    on conflict (id) do nothing;
  end if;
end
$block$;

insert into public.sc_application_schema_versions(version_key, phase, description, notes)
values (
  '202607250601',
  'step_7',
  'Resumable supplier catalog sync run ledger and private source cache',
  'No existing feed or catalog business rows were modified.'
)
on conflict (version_key) do update
set phase = excluded.phase,
    description = excluded.description,
    notes = excluded.notes;

commit;
