-- Step 4: employee authorization and function security audit objects.
-- Additive only. Existing Auth users are seeded as admin to preserve current application access.

create table if not exists public.sc_app_user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'operator' check (role in ('admin', 'manager', 'operator', 'viewer')),
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.sc_app_user_roles is
  'Authorization roles for privileged Netlify functions. Existing Auth users were initially seeded as admin to prevent a production lockout.';

insert into public.sc_app_user_roles (user_id, role, is_active, notes)
select u.id, 'admin', true, 'Seeded during Step 4 to preserve existing employee access.'
from auth.users u
on conflict (user_id) do nothing;

create or replace function public.sc_current_app_role()
returns text
language sql
stable
security definer
set search_path = pg_catalog
as $function$
  select r.role
  from public.sc_app_user_roles r
  where r.user_id = auth.uid()
    and r.is_active = true
  limit 1
$function$;

revoke all on function public.sc_current_app_role() from public;
grant execute on function public.sc_current_app_role() to authenticated;

alter table public.sc_app_user_roles enable row level security;
grant select on public.sc_app_user_roles to authenticated;
revoke insert, update, delete on public.sc_app_user_roles from anon, authenticated;

do $block$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'sc_app_user_roles'
      and policyname = 'Employees can view permitted role records'
  ) then
    create policy "Employees can view permitted role records"
      on public.sc_app_user_roles
      for select
      to authenticated
      using (
        user_id = auth.uid()
        or public.sc_current_app_role() in ('admin', 'manager')
      );
  end if;
end
$block$;

create table if not exists public.sc_function_security_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  function_name text not null,
  action text not null default 'request',
  outcome text not null,
  user_id uuid,
  app_role text,
  request_id text,
  request_origin text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists sc_function_security_audit_created_at_idx
  on public.sc_function_security_audit (created_at desc);
create index if not exists sc_function_security_audit_function_idx
  on public.sc_function_security_audit (function_name, created_at desc);

alter table public.sc_function_security_audit enable row level security;
revoke all on public.sc_function_security_audit from anon, authenticated;

comment on table public.sc_function_security_audit is
  'Service-role-only audit log for privileged Netlify function authorization decisions. Logging failures never block the operational request.';
