-- Skilled Crafting Inventory Application
-- STEP 1: Ensure the active standalone sample-products model has its required objects.
-- ADDITIVE ONLY: existing rows are not moved, changed, or deleted.
-- Existing sample_products and sample_products_with_bins objects are preserved.

begin;

create table if not exists public.sample_product_types (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

alter table public.sample_product_types add column if not exists name text;
alter table public.sample_product_types add column if not exists created_at timestamptz default now();

create table if not exists public.sample_products (
  id bigint generated by default as identity primary key,
  brand text not null,
  style text not null,
  price numeric,
  vendor text,
  color text not null,
  size text not null,
  product_type text,
  customer text,
  quantity integer not null default 1,
  bin_id bigint,
  image_url text,
  image_path text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add only missing columns. Existing column values and types are not rewritten.
alter table public.sample_products add column if not exists brand text;
alter table public.sample_products add column if not exists style text;
alter table public.sample_products add column if not exists price numeric;
alter table public.sample_products add column if not exists vendor text;
alter table public.sample_products add column if not exists color text;
alter table public.sample_products add column if not exists size text;
alter table public.sample_products add column if not exists product_type text;
alter table public.sample_products add column if not exists customer text;
alter table public.sample_products add column if not exists quantity integer default 1;
alter table public.sample_products add column if not exists bin_id bigint;
alter table public.sample_products add column if not exists image_url text;
alter table public.sample_products add column if not exists image_path text;
alter table public.sample_products add column if not exists notes text;
alter table public.sample_products add column if not exists created_at timestamptz default now();
alter table public.sample_products add column if not exists updated_at timestamptz default now();

create index if not exists idx_sample_products_created_at
  on public.sample_products(created_at desc);
create index if not exists idx_sample_products_bin_id
  on public.sample_products(bin_id);
create index if not exists idx_sample_products_search_fields
  on public.sample_products(brand, style, color, size);
create index if not exists idx_sample_product_types_lower_name
  on public.sample_product_types(lower(trim(name)));

create or replace function public.sc_touch_sample_products_updated_at_v1()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'trg_sc_touch_sample_products_updated_at_v1'
      and tgrelid = 'public.sample_products'::regclass
  ) then
    execute 'create trigger trg_sc_touch_sample_products_updated_at_v1 before update on public.sample_products for each row execute function public.sc_touch_sample_products_updated_at_v1()';
  end if;
end $$;

-- Seed only missing lookup names. No existing row is updated.
insert into public.sample_product_types(name)
select requested.name
from unnest(array[
  'Sublimation', 'Tee', 'Hoodie', 'Crew Neck Sweatshirt', 'Athletic Tee',
  '¼ Zip', 'Full Zip Sweatshirt', 'Hat', 'Beanie', 'Pant', 'Short',
  'Polo', 'Tank', 'Jacket', 'Vest', 'Sock', 'Jersey'
]::text[]) as requested(name)
where not exists (
  select 1
  from public.sample_product_types existing
  where lower(trim(existing.name)) = lower(trim(requested.name))
);

-- Create the active display view only when it is missing. An existing view is not replaced.
do $$
begin
  if to_regclass('public.sample_products_with_bins') is null then
    if to_regclass('public.bins') is not null
       and exists (select 1 from information_schema.columns where table_schema='public' and table_name='bins' and column_name='id')
       and exists (select 1 from information_schema.columns where table_schema='public' and table_name='bins' and column_name='bin_code')
       and exists (select 1 from information_schema.columns where table_schema='public' and table_name='bins' and column_name='label')
       and exists (select 1 from information_schema.columns where table_schema='public' and table_name='bins' and column_name='location') then
      execute $view$
        create view public.sample_products_with_bins as
        select
          sp.*,
          b.bin_code,
          b.label as bin_label,
          b.location as bin_location
        from public.sample_products sp
        left join public.bins b on b.id = sp.bin_id
      $view$;
    else
      execute $view$
        create view public.sample_products_with_bins as
        select
          sp.*,
          null::text as bin_code,
          null::text as bin_label,
          null::text as bin_location
        from public.sample_products sp
      $view$;
    end if;
  end if;
end $$;

comment on table public.sample_products is
  'Authoritative standalone sample inventory used by the active application sample page.';
comment on table public.sample_product_types is
  'Lookup values for the authoritative standalone sample-products model.';

-- Preserve existing access and add the minimum authenticated grants expected by the employee app.
grant select, insert, update, delete on public.sample_products to authenticated;
grant select, insert, update, delete on public.sample_product_types to authenticated;
grant select on public.sample_products_with_bins to authenticated;

do $$
begin
  if to_regclass('public.sample_products_id_seq') is not null then
    execute 'grant usage, select on sequence public.sample_products_id_seq to authenticated';
  end if;
  if to_regclass('public.sample_product_types_id_seq') is not null then
    execute 'grant usage, select on sequence public.sample_product_types_id_seq to authenticated';
  end if;
end $$;

commit;
